.libPaths("")

library(optparse)

option_list <- list(
    make_option(c("--sce"),
        type = "character", default = NULL,
        help = "comma separated list of ALL SingleCellExperiment/Seurat files generated by 'preprocessData.R'"
    ),
    make_option(c("--baseCond"),
        type = "character", default = NULL,
        help = "Reference condition the barcode IDs are derived from"
    ),
    make_option(c("--outdir"),
        type = "character", default = "annotated",
        help = "directory the annotated objects are written to, default 'annotated'"
    ),
    make_option(c("--out"),
        type = "character", default = "CaTCHseq",
        help = "prefix of the barcode ID mapping table"
    ),
    make_option(c("--libpath"),
        type = "character", default = "/tools/scripts/R/",
        help = "path to R libs, trailing slash is required"
    )
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$baseCond)) {
    print_help(opt_parser)
    stop("Not enough parameters")
}

#### Source Functions ####
source(paste0(opt$libpath, "singlecell_utils.R"))

########################################################
library(tidyverse)
library(SingleCellExperiment)
library(Seurat)
options(Seurat.object.assay.version = "v5")
library(R.filesets)

#### Assign run wide CaTCH barcode IDs ####
# 'preprocessData.R' runs on a single library, which holds a single condition, so
# it can neither see the reference condition of the run nor produce IDs that are
# comparable between libraries. The IDs are therefore ranked ONCE here from the
# pooled cells of the reference condition and then written into every object of
# the run, so all of them carry the same CaTCH.BC_ID for the same barcode.

paths <- split_SCE_paths(opt$sce)
dir.create(opt$outdir, showWarnings = FALSE, recursive = TRUE)

# Metadata of any object type, Seurat and SingleCellExperiment alike.
get_cell_meta <- function(x) {
    if (inherits(x, "Seurat")) {
        x@meta.data
    } else {
        as.data.frame(SummarizedExperiment::colData(x))
    }
}

# The Seurat objects and the plain SCE objects of a library hold the same cells,
# so the ranking is built from the Seurat objects only to avoid counting every
# cell twice. Without a Seurat object all provided files are used.
seurat_paths <- grep("_seurat_sce", paths, value = TRUE)
map_paths <- if (length(seurat_paths) > 0) seurat_paths else paths

print(sprintf("Building the barcode ID map from %d of %d object(s) ...", length(map_paths), length(paths)))

mds <- vector("list", length(map_paths))
for (i in seq_along(map_paths)) {
    obj <- loadRDS(map_paths[i])
    md <- get_cell_meta(obj)
    keep <- intersect(c("CaTCH.Status", "CaTCH.BC_unique", "Condition", "Replicate"), colnames(md))
    mds[[i]] <- md[, keep, drop = FALSE]
    rm(obj, md)
    gc(verbose = FALSE)
}

shared <- Reduce(intersect, lapply(mds, colnames))
cellmeta <- do.call(rbind, lapply(mds, function(x) x[, shared, drop = FALSE]))
rownames(cellmeta) <- NULL
rm(mds)
gc(verbose = FALSE)

print(sprintf(
    "Pooled %d cells covering the condition(s): %s",
    nrow(cellmeta), paste(sort(unique(as.character(cellmeta$Condition))), collapse = ", ")
))

bc_map <- NULL
if (!opt$baseCond %in% as.character(cellmeta$Condition)) {
    print(sprintf(
        "WARNING: the reference condition '%s' is not present in any of the objects, the barcode IDs are left untouched.",
        opt$baseCond
    ))
} else {
    bc_map <- build_BC_ID_map(cellmeta, opt$baseCond)
    write.table(bc_map, paste0(opt$out, "_CaTCH_barcode_IDs.tsv"),
        sep = "\t", quote = FALSE, row.names = FALSE
    )
}
rm(cellmeta)
gc(verbose = FALSE)

#### Write the IDs into every object ####
for (i in seq_along(paths)) {
    obj <- loadRDS(paths[i])
    outfile <- file.path(opt$outdir, basename(paths[i]))

    if (!is.null(bc_map)) {
        md <- get_cell_meta(obj)
        if (!"CaTCH.BC_unique" %in% colnames(md)) {
            print(sprintf("   %s carries no CaTCH barcodes, copied unchanged.", basename(paths[i])))
        } else {
            ids <- apply_BC_ID_map(md$CaTCH.BC_unique, bc_map)
            if (inherits(obj, "Seurat")) {
                obj@meta.data$CaTCH.BC_ID <- ids
            } else {
                SummarizedExperiment::colData(obj)$CaTCH.BC_ID <- ids
            }
            print(sprintf(
                "   %s: %d of %d cells carry a ranked barcode ID.",
                basename(paths[i]), sum(as.character(ids) != "BC_0"), length(ids)
            ))
        }
    }

    saveRDS(obj, file = outfile, compress = "gzip")
    rm(obj)
    gc(verbose = FALSE)
}

print(sprintf("Wrote %d annotated object(s) to '%s'.", length(paths), opt$outdir))
