.libPaths("")

library(optparse)

option_list <- list(
    make_option(c("--sce"),
        type = "character", default = NULL,
        help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"
    ),
    make_option(c("--format"),
        type = "character", default = "pdf",
        help = "format of the plots: pdf (default), jpeg, png, tiff"
    ),
    make_option(c("--width"),
        type = "numeric", default = 30,
        help = "width of the plot. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--height"),
        type = "numeric", default = 15,
        help = "height of the plot. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--out"),
        type = "character", default = NULL,
        help = "path to the output file"
    )
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)) {
    print_help(opt_parser)
    stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if ((length(opt$format) == 0) || !(opt$format %in% c("pdf", "png", "jpeg", "tiff"))) {
    opt$format <- "pdf"
}

##### Additional methods #####
createValueDistrPlot <- function(sce, grp.col = "Cluster", val.col = "CMO", colors = NULL, grp.order = NULL, xlab = NULL, ylab = NULL, title = NULL) {
    if (is.null(sce)) {
        stop("'sce' must be specified and cannot be NULL")
    }

    plot.data <- sce@meta.data %>%
        dplyr::count(.data[[grp.col]], .data[[val.col]]) %>%
        dplyr::group_by(.data[[grp.col]]) %>%
        dplyr::mutate(Proportion = n / sum(n) * 100)
    if (!is.null(grp.order)) {
        tmp <- tibble()
        for (x in grp.order) {
            tmp <- rbind(tmp, plot.data[which(plot.data[[grp.col]] == x), ])
        }
        tmp[[grp.col]] <- factor(tmp[[grp.col]], levels = grp.order)
        plot.data <- tmp
    }
    plot <- ggplot2::ggplot(data = plot.data, ggplot2::aes(fill = .data[[val.col]], x = .data[[grp.col]], y = Proportion)) +
        ggplot2::geom_bar(position = "stack", stat = "identity")
    if (!is.null(colors)) {
        plot <- plot + ggplot2::scale_fill_manual(values = colors)
    }
    if (!is.null(xlab)) {
        plot <- plot + ggplot2::xlab(xlab)
    }
    if (!is.null(ylab)) {
        plot <- plot + ggplot2::ylab(ylab)
    }
    if (!is.null(title)) {
        plot <- plot + ggplot2::ggtitle(title)
    }
    return(plot)
}

########################################################
library(tidyverse)
library(gridExtra)
library(scater)
library(scran)
library(SingleCellExperiment)
library(Seurat)
# options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")
library(SeuratWrappers)
library(sctransform)
library(R.filesets)

#### Load single cell data generated by the NF pipeline ####
sce <- loadRDS(opt$sce)

### Switching to integrated assay ###
if (DefaultAssay(sce) != "RNA_integrated.cca") {
    DefaultAssay(sce) <- "RNA_integrated.cca" # DefaultAssay(sce) <- "RNA_integrated.cca"
}

#### Plots ####

##### Plot cell count vs mito content by Category #####

qcout <- paste0(opt$out, "_QC_MT_content_filtered.", opt$format)
if (opt$format == "png") {
    png(filename = qcout, width = opt$width, height = opt$height)
} else if (opt$format == "jpeg") {
    jpeg(filename = qcout, width = opt$width, height = opt$height)
} else if (opt$format == "tiff") {
    tiff(filename = qcout, width = opt$width, height = opt$height)
} else {
    pdf(file = qcout, width = opt$width, height = opt$height)
}

FeatureScatter(sce, feature1 = "nCount_RNA", feature2 = "percent.mt", group.by = "Phase")
dev.off()

qcout <- paste0(opt$out, "_QC_Feature_content_filtered.", opt$format)
if (opt$format == "png") {
    png(filename = qcout, width = opt$width, height = opt$height)
} else if (opt$format == "jpeg") {
    jpeg(filename = qcout, width = opt$width, height = opt$height)
} else if (opt$format == "tiff") {
    tiff(filename = qcout, width = opt$width, height = opt$height)
} else {
    pdf(file = qcout, width = opt$width, height = opt$height)
}

FeatureScatter(sce, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", group.by = "Phase")
dev.off()

## Plot UMAPs
reduction.name <- "umap_pca"
p.umap_noint_clusters <- DimPlot(sce, reduction = reduction.name, group.by = "integrated.cca_cluster", label.size = 1, alpha = .3) +
    ggtitle("Overview by non-integrated cluster") +
    guides(colour = guide_legend(override.aes = list(size = 2)), shape = "none")

p.umap_noint_samples <- DimPlot(sce, reduction = reduction.name, group.by = "Sample", label.size = 1, alpha = .3) +
    ggtitle("Overview by non-integrated samples") +
    guides(colour = guide_legend(override.aes = list(size = 2)), shape = "none")

reduction.name <- "umap_integrated.cca"

p.umap_clusters <- DimPlot(sce, reduction = reduction.name, group.by = "integrated.cca_cluster", label.size = 1, alpha = .3) +
    ggtitle("Overview by cluster") +
    guides(colour = guide_legend(override.aes = list(size = 2)), shape = "none")

p.umap_samples <- DimPlot(sce, reduction = reduction.name, group.by = "Sample", label.size = 1, alpha = .3) +
    ggtitle("Overview by samples") +
    guides(colour = guide_legend(override.aes = list(size = 2)), shape = "none")
# LabelClusters(plot = p.umap_samples, id = "ident")


## Add additional labels
# LabelClusters(plot = plot, id = "ident")
# LabelPoints(plot = plot, points = TopCells(object = pbmc3k.final[["pca"]]), repel = TRUE)

status.colors <- list(
    "Singlet" = "forestgreen",
    "Putative singlet" = "orange",
    "Multiplet" = "red",
    "No barcode" = "grey50"
)
p.status_distr <- DimPlot(sce, reduction = reduction.name, group.by = "CaTCH.Status", label.size = 1, alpha = .2) + # , ylab = "Proportion, [%]") +
    ggtitle("CaTCH status per sample") +
    guides(colour = guide_legend(override.aes = list(size = 4))) +
    scale_color_manual(values = status.colors, name = "Catch.Status")

p.status_distr_cluster <- createValueDistrPlot(sce,
    grp.col = "integrated.cca_cluster",
    val.col = "CaTCH.Status",
    colors = status.colors,
    ylab = "Proportion, [%]",
    title = "CaTCH status per cluster"
) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    guides(fill = guide_legend("CaTCH status"))

p.status_distr_samples <- createValueDistrPlot(sce,
    grp.col = "Sample",
    val.col = "CaTCH.Status",
    colors = status.colors,
    ylab = "Proportion, [%]",
    title = "CaTCH status per sample"
) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    guides(fill = guide_legend("CaTCH status"))

p.cluster_size <- sce@meta.data %>%
    select(integrated.cca_cluster) %>%
    group_by(integrated.cca_cluster) %>%
    mutate(n = n()) %>%
    ungroup() %>%
    distinct(integrated.cca_cluster, n) %>%
    ggplot() +
    geom_col(aes(x = integrated.cca_cluster, y = n)) +
    xlab("Cluster") +
    ylab("Cell count") +
    ggtitle("Cluster sizes") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

cs.color <- list(
    "G0" = "gray75",
    "G1" = "#FDB916",
    "G2M" = "#11B09C",
    "M" = "#D22248",
    "MG1" = "#F17724",
    "S" = "#BECE2D"
)

p.umap_cellstage <- DimPlot(sce, reduction = reduction.name, group.by = "Phase", label.size = 2, alpha = .2) +
    ggtitle("Overview by cell stage") +
    scale_color_manual(values = cs.color, name = "Cell stage") +
    guides(color = guide_legend("Cell stage", override.aes = list(size = 4))) # +
# guides(colour = guide_legend(override.aes = list(size = 10))) +


sce@meta.data$CellStatus <- "Proliferating"
sce@meta.data$CellStatus[sce@meta.data$S.Score < 0 & sce@meta.data$G2M.Score < 0] <- "Quiescent" # We have no clear G0, need to fix this somehow, Seurat suggests Cell-types which are very proliferative would have a higher fraction of cells in S/G2M whereas the cell types with low S/G2M fraction would be terminally differentiated, slowly dividing or quiescent cells
p.umap_cellstatus <- DimPlot(sce, reduction = reduction.name, group.by = "CellStatus") +
    ggtitle("Overview by cell status") +
    guides(colour = guide_legend(override.aes = list(size = 4))) +
    scale_color_manual(values = c("Proliferating" = "forestgreen", "Quiescent" = "gray75"), name = "Cell status")

p.cellstage_distr <- createValueDistrPlot(sce,
    grp.col = "integrated.cca_cluster",
    val.col = "Phase",
    colors = cs.color,
    ylab = "Proportion, [%]",
    title = "Cell stage per cluster"
) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    guides(fill = guide_legend("Cell cycle stage"))

p.cellstage_samples_distr <- createValueDistrPlot(sce,
    grp.col = "Sample",
    val.col = "Phase",
    colors = cs.color,
    ylab = "Proportion, [%]",
    title = "Cell stage per sample"
) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    guides(fill = guide_legend("Cell cycle stage"))


p.unique_bc_distr <- sce@meta.data %>%
    filter(CaTCH.Status == "Singlet") %>%
    select(Sample, CaTCH.BCs) %>%
    group_by(Sample) %>%
    summarise(Unique = n_distinct(CaTCH.BCs)) %>%
    ggplot() +
    geom_col(aes(x = Sample, y = Unique)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    xlab("Sample") +
    ylab("Unique CaTCH barcodes") +
    ggtitle("Unique CaTCH barcodes per sample")


out <- paste0(opt$out, ".", opt$format)
if (opt$format == "png") {
    png(filename = out, width = opt$width, height = opt$height * 2)
} else if (opt$format == "jpeg") {
    jpeg(filename = out, width = opt$width, height = opt$height * 2)
} else if (opt$format == "tiff") {
    tiff(filename = out, width = opt$width, height = opt$height * 2)
} else {
    pdf(file = out, width = opt$width, height = opt$height * 2)
}
print(grid.arrange(
    p.umap_clusters, # 1
    p.umap_samples, # 2
    p.status_distr, # 3
    p.cluster_size, # 4
    p.umap_cellstage, # 5
    p.umap_cellstatus, # 6
    p.cellstage_distr, # 7
    p.cellstage_samples_distr, # 8
    p.status_distr_cluster, # 9
    p.status_distr_samples, # 10
    p.unique_bc_distr, # 11
    p.umap_noint_clusters, # 12
    p.umap_noint_samples, # 13
    layout_matrix = rbind(
        c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2),
        c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2),
        c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2),
        c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2),
        c(3, 3, 3, 11, 11, 11, 4, 4, 4, 4),
        c(3, 3, 3, 11, 11, 11, 4, 4, 4, 4),
        c(3, 3, 3, 11, 11, 11, 4, 4, 4, 4),
        c(5, 5, 5, 6, 6, 6, 9, 9, 9, 9),
        c(5, 5, 5, 6, 6, 6, 9, 9, 9, 9),
        c(5, 5, 5, 6, 6, 6, 9, 9, 9, 9),
        c(7, 7, 7, 8, 8, 8, 10, 10, 10, 10),
        c(7, 7, 7, 8, 8, 8, 10, 10, 10, 10),
        c(7, 7, 7, 8, 8, 8, 10, 10, 10, 10),
        c(12, 12, 12, 12, 12, 13, 13, 13, 13, 13),
        c(12, 12, 12, 12, 12, 13, 13, 13, 13, 13),
        c(12, 12, 12, 12, 12, 13, 13, 13, 13, 13),
        c(12, 12, 12, 12, 12, 13, 13, 13, 13, 13)
        # c(NA, NA, NA, NA, 11, 11, 11, 11, NA, NA),
        # c(NA, NA, NA, NA, 11, 11, 11, 11, NA, NA),
        # c(NA, NA, NA, NA, 11, 11, 11, 11, NA, NA)
    )
))

dev.off()