.libPaths("")

library(optparse)

option_list = list(
  make_option(c("--sce"), type="character", default = NULL, 
              help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"),
  make_option(c("--format"), type="character", default = "pdf", 
              help = "format of the plots: pdf (default), jpeg, png, tiff"),
  make_option(c("--width"), type="numeric", default = 25, 
              help = "width of the plot. The units depend on the format: inches for PDF, pixels otherwise"),
  make_option(c("--height"), type = "numeric", default = 10, 
              help = "height of the plot. The units depend on the format: inches for PDF, pixels otherwise"),
  make_option(c("--out"), type="character", default = NULL, 
              help = "path to the output file")
)

opt_parser = OptionParser(option_list = option_list)
opt = parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)){
  print_help(opt_parser)
  stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if ( (length(opt$format) == 0) || !(opt$format %in% c("pdf", "png", "jpeg", "tiff")) ) {
  opt$format <- "pdf"
}

##### Additional methods #####
createValueDistrPlot <- function(sce, grp.col = "Cluster", val.col = "CMO", colors = NULL, grp.order = NULL, xlab = NULL, ylab = NULL, title = NULL) {
  
  if (is.null(sce)) {
    stop("'sce' must be specified and cannot be NULL")
  }
  
  plot.data <- colData(sce) %>%
               tibble::as_tibble() %>%
               dplyr::count(.data[[grp.col]], .data[[val.col]]) %>%
               dplyr::group_by(.data[[grp.col]]) %>%
               dplyr::mutate(Proportion = n / sum(n) * 100)
  if (!is.null(grp.order)) {
    tmp <- tibble()
    for (x in grp.order) {
      tmp <- rbind(tmp, plot.data[which(plot.data[[grp.col]] == x),])
    }
    tmp[[grp.col]] <- factor(tmp[[grp.col]], levels = grp.order)
    plot.data <- tmp
  }
  plot <- ggplot2::ggplot(data = plot.data, ggplot2::aes(fill = .data[[val.col]], x = .data[[grp.col]], y = Proportion)) +
            ggplot2::geom_bar(position = "stack", stat="identity")
  if(!is.null(colors)) {
    plot <- plot + ggplot2::scale_fill_manual(values = colors)
  }
  if(!is.null(xlab)) {
    plot <- plot + ggplot2::xlab(xlab)
  }
  if(!is.null(ylab)) {
    plot <- plot + ggplot2::ylab(ylab)
  }
  if(!is.null(title)) {
    plot <- plot + ggplot2::ggtitle(title)
  }
  return (plot)
}

########################################################
library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(gridExtra)

#### Load single cell data generated by the NF pipeline ####
load(opt$sce)


#### Plots ####
##### Overview tSNE plot #####
p.tsne_treatments <- plotReducedDim(sce, dimred = "TSNE", colour_by = "Treatment", text_by = "Cluster", point_size = 1, point_alpha = 0.7) +
                      ggtitle("Overview by treatment") + 
                      guides(colour = guide_legend(override.aes = list(size = 10)))

p.tsne_clusters <- plotReducedDim(sce, dimred = "TSNE", colour_by = "Cluster", text_by = "Cluster", point_size = 1, point_alpha = 0.7) +
                    ggtitle("Overview by cluster") + 
                    guides(colour = guide_legend(override.aes = list(size = 5)))

status.colors <- list("Singlet" = "forestgreen",
                      "Putative singlet" = "orange",
                      "Multiplet" = "red",
                      "No barcode" = "grey50")
p.status_distr <- createValueDistrPlot(sce,
                                       grp.col = "Sample",
                                       val.col = "CaTCH.Status",
                                       colors = status.colors,
                                       ylab = "Proportion, [%]",
                                       title = "CaTCH status per sample") + 
                    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
                    guides(fill = guide_legend("CaTCH status"))

p.status_distr_cluster <- createValueDistrPlot(sce,
                                       grp.col = "Cluster",
                                       val.col = "CaTCH.Status",
                                       colors = status.colors,
                                       ylab = "Proportion, [%]",
                                       title = "CaTCH status per cluster") + 
                            theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
                            guides(fill = guide_legend("CaTCH status"))

p.cluster_size <- colData(sce) %>%
                  as_tibble() %>%
                  select(Cluster) %>%
                  group_by(Cluster) %>%
                  mutate(n = n()) %>%
                  ungroup() %>%
                  distinct(Cluster, n) %>%
                  ggplot() + 
                    geom_col(aes(x = Cluster, y = n)) + 
                    xlab("Cluster") + 
                    ylab("Cell count") + 
                    ggtitle("Cluster sizes") + 
                    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

p.tsne_per_sample <- plotReducedDim(sce, dimred = "TSNE", colour_by = "CaTCH.Status", other_fields = c("Treatment", "Replicate"), point_size = 1, point_alpha = 0.7) +
                      ggtitle("Overview per treatment and replicate") + 
                      guides(colour = guide_legend(override.aes = list(size = 10))) + 
                      scale_color_manual(values = status.colors, name = "CaTCH status") +
                      facet_grid(rows = vars(Treatment), cols = vars(Replicate), switch = "y")


cs.color <- list("G0" = "gray75",
                 "G1S" = "#FDB916",
                 "G2M" = "#11B09C",
                 "M" = "#D22248",
                 "MG1" = "#F17724",
                 "S" = "#BECE2D")
p.tsne_cellstage <- plotReducedDim(sce, dimred = "TSNE", colour_by = "CellStage", text_by = "Cluster", point_size = 1, point_alpha = 0.7) +
                      ggtitle("Overview by cell stage") + 
                      guides(colour = guide_legend(override.aes = list(size = 10))) +
                      scale_color_manual(values = cs.color, name = "Cell stage") +
                      guides(color = guide_legend("Cell stage"))

sce$CellStatus <- "Proliferating"
sce$CellStatus[sce$CellStage == "G0"] <- "Quiescent"
p.tsne_cellstatus <- plotReducedDim(sce, dimred = "TSNE", colour_by = "CellStatus", text_by = "Cluster", point_size = 1, point_alpha = 0.7) +
                      ggtitle("Overview by cell status") + 
                      guides(colour = guide_legend(override.aes = list(size = 10))) + 
                      scale_color_manual(values = c("Proliferating" = "forestgreen", "Quiescent" = "gray75"), 
                                         name = "Cell status")

p.cellstage_distr <- createValueDistrPlot(sce,
                                          grp.col = "Cluster",
                                          val.col = "CellStage",
                                          colors = cs.color,
                                          ylab = "Proportion, [%]",
                                          title = "Cell stage per cluster") + 
                      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
                      guides(fill = guide_legend("Cell cycle stage"))

p.unique_bc_distr <- colData(sce) %>% 
                     as_tibble() %>% 
                     filter(CaTCH.Status == "Singlet") %>% 
                     select(Sample, CaTCH.BCs) %>% 
                     group_by(Sample) %>% 
                     summarise(Unique = n_distinct(CaTCH.BCs)) %>%
                     ggplot() + 
                      geom_col(aes(x = Sample, y = Unique)) + 
                      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
                      xlab("Sample") + 
                      ylab("Unique CaTCH barcodes") + 
                      ggtitle("Unique CaTCH barcodes per sample")

p.treatment_distr <- createValueDistrPlot(sce,
                                          grp.col = "Cluster",
                                          val.col = "Treatment",
                                          ylab = "Proportion, [%]",
                                          title = "Treatment per cluster") + 
                      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


p.tsne_vpr <- plotReducedDim(sce, dimred = "TSNE", colour_by = "dCas9-VPR", text_by = "Cluster", point_size = 1, point_alpha = 0.7) +
                ggtitle("Overview of dCas9-VPR expression") + 
                guides(col = guide_legend("logcounts"))

p.tsne_gfp <- plotReducedDim(sce, dimred = "TSNE", colour_by = "GFP", text_by = "Cluster", point_size = 1, point_alpha = 0.7) +
                ggtitle("Overview of GFP expression") + 
                guides(col = guide_legend("logcounts"))

p.tsne_bfp <- plotReducedDim(sce, dimred = "TSNE", colour_by = "tagBFP", text_by = "Cluster", point_size = 1, point_alpha = 0.7) +
                ggtitle("Overview of BFP expression") + 
                guides(col = guide_legend("logcounts"))

p.tsne_ki67 <- plotReducedDim(sce, dimred = "TSNE", colour_by = "MKI67", text_by = "Cluster", point_size = 1, point_alpha = 0.7) +
                ggtitle("Overview of KI67 expression") + 
                guides(col = guide_legend("logcounts"))

if (opt$format == "png") {
  png(filename = opt$out, width = opt$width, height = opt$height)
} else if (opt$format == "jpeg") {
  jpeg(filename = opt$out, width = opt$width, height = opt$height)
} else if (opt$format == "tiff") {
  tiff(filename = opt$out, width = opt$width, height = opt$height)
} else {
  pdf(file = opt$out, width = opt$width, height = opt$height)
}
grid.arrange(p.tsne_treatments,            # 1
             p.tsne_clusters,              # 2
             p.cluster_size,               # 3
             p.treatment_distr,            # 4
             p.tsne_per_sample,            # 5
             p.tsne_cellstage,             # 6
             p.tsne_cellstatus,            # 7
             p.cellstage_distr,            # 8
             p.status_distr_cluster,       # 9
             p.unique_bc_distr,            # 10
             p.status_distr,               # 11
             p.tsne_vpr,                   # 12
             p.tsne_gfp,                   # 13
             p.tsne_bfp,                   # 14
             p.tsne_ki67,                  # 15
             layout_matrix = rbind(c(1, 1, 2, 2, 5, 5, 5, 5),
                                   c(1, 1, 2, 2, 5, 5, 5, 5),
                                   c(3, 3, 4, 4, 5, 5, 5, 5),
                                   c(6, 6, 7, 7, 8, 8,10,10),
                                   c(6, 6, 7, 7, 9, 9,11,11),
                                   c(12,12,13,13,14,14,15,15),
                                   c(12,12,13,13,14,14,15,15)))

dev.off()
