.libPaths("")

library(optparse)

option_list <- list(
    make_option(c("--sce"),
        type = "character", default = NULL,
        help = "comma separated list of the SingleCellExperiment files generated by 'preprocessData.R'"
    ),
    make_option(c("--baseCond"),
        type = "character", default = NULL,
        help = "Base condition for DE Analysis"
    ),
    make_option(c("--plots_per_row"),
        type = "numeric", default = 5,
        help = "number of barcode plots per row of the output plot"
    ),
    make_option(c("--format"),
        type = "character", default = "pdf",
        help = "format of the plots: pdf (default), jpeg, png, tiff"
    ),
    make_option(c("--width"),
        type = "numeric", default = 20,
        help = "width of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--height"),
        type = "numeric", default = 25,
        help = "height of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--pcut"),
        type = "numeric", default = 0.1,
        help = "Cutoff for pvalues, default(0.1)"
    ),
    make_option(c("--fcut"),
        type = "numeric", default = 1,
        help = "Cutoff for lFC, default(1)"
    ),
    make_option(c("--out"),
        type = "character", default = NULL,
        help = "path to the output file"
    ),
    make_option(c("--libpath"),
        type = "character", default = "/tools/scripts/R/",
        help = "path to R libs, trailing slash is required"
    )
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)) {
    print_help(opt_parser)
    stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if (!(opt$format %in% c("pdf", "png", "jpeg", "tiff"))) {
    opt$format <- "pdf"
}


#### Source Functions ####
source(paste0(opt$libpath, "singlecell_utils.R"))

########################################################
library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(Seurat)
# options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")
library(SeuratWrappers)
library(gridExtra)
library(DESeq2)
library(edgeR)
library(apeglm)
library(EnhancedVolcano)
library(sctransform)
library(R.filesets)

#### Load single cell data generated by the NF pipeline ####
#### Use DeSeq2/EdgeR to identify over- and underrepresented barcodes ####
# The barcode counts are taken from the cell metadata of ALL SCE files of the
# run, so the count matrix covers every condition and replicate.
cellmeta <- collect_SCE_metadata(opt$sce)

# CaTCH.BC_ID is ranked for the whole run by 'assign_barcode_ids.R'. It is only
# rebuilt here when the provided objects did not go through that step, because
# 'preprocessData.R' alone leaves every cell at 'BC_0'.
cellmeta <- ensure_global_BC_IDs(cellmeta, opt$baseCond)

### collect metadata ###
metadata <- cellmeta %>%
    dplyr::select(Condition, Replicate) %>%
    distinct()

### set reference condition ###
ref.Condition <- opt$baseCond

### Count Barcodes ###
bc.counts <- cellmeta %>%
    filter((CaTCH.Status == "Singlet" | CaTCH.Status == "Double_Integration") & CaTCH.BC_ID != "BC_0") %>%
    dplyr::select(CaTCH.BC_unique, Replicate, CaTCH.BC_ID) %>%
    group_by(CaTCH.BC_unique, Replicate) %>%
    mutate(n = n()) %>%
    ungroup() %>%
    distinct() %>%
    pivot_wider(names_from = Replicate, values_from = n, values_fill = 0) %>%
    filter(rowSums(across(starts_with(paste0(ref.Condition, "_")))) > 0) %>%
    drop_na()

### dplyr::select metadata ###
# 'Replicate' is the sample level of the barcode counts ('<Condition>_<replicate>')
# and is used to match the count columns to the rows of the metadata, so the same
# name normalisation has to be applied to both.
metadata <- metadata %>%
    mutate(Condition = as.factor(gsub("-", ".", Condition))) %>%
    mutate(Replicate = as.character(gsub("-", ".", Replicate))) %>%
    dplyr::select(Condition, Replicate) %>%
    as.data.frame()
row.names(metadata) <- NULL

# Check if reference condition is present in the metadata
if(!ref.Condition %in% metadata$Condition){    
    saveRDS(metadata, file = paste0(opt$out, "_DE_list.rds.gz"), compress = "gzip")
    stop("Reference condition not found in the metadata")
}

### Run pairwise DE Analysis for BCs ###
countData <- bc.counts %>%
    dplyr::select(-CaTCH.BC_unique) %>%
    column_to_rownames(var = "CaTCH.BC_ID") %>%
    rename_with(~ gsub("-", ".", .x))

# Samples without a single counted barcode have no column in the count table and
# are dropped from the metadata, otherwise the count columns could not be matched
# to the metadata rows.
missing <- setdiff(metadata$Replicate, colnames(countData))
if (length(missing) > 0) {
    print(sprintf("   No counted barcodes for the sample(s) '%s', they are excluded.", paste(missing, collapse = ", ")))
    metadata <- metadata[!metadata$Replicate %in% missing, , drop = FALSE]
    metadata$Condition <- droplevels(metadata$Condition)
}
countData <- countData %>% dplyr::select(dplyr::all_of(metadata$Replicate))

# Number of replicates per condition, used to decide between DESeq2 and edgeR.
replicates_per_condition <- table(as.character(metadata$Condition))

comparison_objs <- list()
for (t in setdiff(levels(metadata$Condition), ref.Condition)) {
    print(sprintf("Processing the Condition '%s'...", t))

    contrast_name <- paste(t, ref.Condition, sep = "-vs-")
    detool <- "DESEQ2"
    # DESeq2 needs at least two replicates in BOTH contrasted conditions to
    # estimate the dispersion, edgeR is used with a fixed BCV otherwise. The
    # replicates of the contrast are counted here, the previous check compared a
    # vector against twice its own length and therefore never selected DESeq2.
    if (min(replicates_per_condition[[t]], replicates_per_condition[[ref.Condition]]) >= 2) {
        print("Enough replicates found, running DESeq2")

        ddslist <- run_deseq_bcs(contrast_name, metadata, countData)
    } else {
        print("Not enough replicates found, running edgeR")
        detool <- "EDGER"
        ddslist <- run_edger_bcs(contrast_name, metadata, countData)
    }
    comparison_objs[[contrast_name]] <- ddslist

    r <- ddslist[["res"]]

    if (nrow(r) > 1) {
        write.table(as.data.frame(r), gzfile(paste("DE_", detool, "_", contrast_name, "_BCs_fdr", opt$pcut, ".tsv.gz", sep = "")), sep = "\t", row.names = FALSE, quote = F)

        pdf(
            file = paste("DE_", detool, "_", contrast_name, "_BCs_Volcano_p", opt$pcut, "_lfc", opt$fcut, ".pdf", sep = ""),
            width = 15, height = 10
        )
        print(EnhancedVolcano(r,
            lab = rownames(r),
            x = "log2FoldChange",
            y = "p.adj",
            title = paste0(contrast_name, "_p", opt$pcut, "_lfc", opt$fcut, sep = ""),
            pCutoff = opt$pcut,
            FCcutoff = opt$fcut,
            pointSize = 3.0,
            labSize = 5.0,
            colAlpha = .3,
            legendLabels = c(
                "Not sig.", "Log (base 2) FC", "p-value",
                "p-value & Log (base 2) FC"
            ),
            legendPosition = "right",
            legendLabSize = 10,
            legendIconSize = 5.0,
            drawConnectors = TRUE,
            widthConnectors = 0.75
        ))
        dev.off()
    } else {
        pdf(file = paste("DE", detool, "_", contrast_name, "BCs_Volcano", "p005_lfc15.pdf", sep = "_"), width = 15, height = 10)
        print(paste("No significantly differential Barcodes found for ", contrast_name))
        dev.off()
    }
    rm(r, ddslist)
}

saveRDS(comparison_objs, file = paste0(opt$out, "_DE_list.rds.gz"), compress = "gzip")
