.libPaths("")

library(optparse)

option_list <- list(
    make_option(c("--sce"),
        type = "character", default = NULL,
        help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"
    ),
    make_option(c("--baseCond"),
        type = "character", default = NULL,
        help = "Base condition for DE Analysis"
    ),
    make_option(c("--plots_per_row"),
        type = "numeric", default = 5,
        help = "number of barcode plots per row of the output plot"
    ),
    make_option(c("--format"),
        type = "character", default = "pdf",
        help = "format of the plots: pdf (default), jpeg, png, tiff"
    ),
    make_option(c("--width"),
        type = "numeric", default = 20,
        help = "width of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--height"),
        type = "numeric", default = 25,
        help = "height of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--pcut"),
        type = "numeric", default = 0.1,
        help = "Cutoff for pvalues, default(0.1)"
    ),
    make_option(c("--fcut"),
        type = "numeric", default = 1,
        help = "Cutoff for lFC, default(1)"
    ),
    make_option(c("--out"),
        type = "character", default = NULL,
        help = "path to the output file"
    ),
    make_option(c("--libpath"),
        type = "character", default = "/tools/scripts/R/",
        help = "path to R libs, trailing slash is required"
    )
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)) {
    print_help(opt_parser)
    stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if (!(opt$format %in% c("pdf", "png", "jpeg", "tiff"))) {
    opt$format <- "pdf"
}


#### Source Functions ####
source(paste0(opt$libpath, "singlecell_utils.R"))

########################################################
library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(Seurat)
# options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")
library(SeuratWrappers)
library(gridExtra)
library(DESeq2)
library(edgeR)
library(apeglm)
library(EnhancedVolcano)
library(sctransform)
library(R.filesets)

#### Load single cell data generated by the NF pipeline ####
sce <- loadRDS(opt$sce)

if (DefaultAssay(sce) != "RNA") {
    DefaultAssay(sce) <- "RNA" # NOT "RNA_integrated.cca"
}
#### Use DeSeq2/EdgeR to identify over- and underrepresented barcodes ####

### collect metadata ###
metadata <- sce@meta.data %>%
    dplyr::select(Condition, Replicate) %>%
    distinct()

### set reference condition ###
ref.Condition <- opt$baseCond

### Count Barcodes ###
bc.counts <- sce@meta.data %>%
    filter((CaTCH.Status == "Singlet" | CaTCH.Status == "Double_Integration") & CaTCH.BC_ID != "BC_0") %>%
    dplyr::select(CaTCH.BC_unique, Replicate, CaTCH.BC_ID) %>%
    group_by(CaTCH.BC_unique, Replicate) %>%
    mutate(n = n()) %>%
    ungroup() %>%
    distinct() %>%
    pivot_wider(names_from = Replicate, values_from = n, values_fill = 0) %>%
    filter(rowSums(across(starts_with(ref.Condition))) > 0) %>%
    drop_na()

### dplyr::select metadata ###
metadata <- metadata %>%
    mutate(Condition = as.factor(gsub("-", ".", Condition))) %>%
    mutate(Replicate = as.factor(gsub("-", ".", Replicate))) %>%
    dplyr::select(Condition, Replicate)
row.names(metadata) <- metadata$Sample

# Check if reference condition is present in the metadata
if(!ref.Condition %in% metadata$Condition){    
    saveRDS(metadata, file = paste0(opt$out, "_DE_list.rds.gz"), compress = "gzip")
    stop("Reference condition not found in the metadata")
}

### Run pairwise DE Analysis for BCs ###
countData <- bc.counts %>%
    dplyr::select(-CaTCH.BC_unique) %>%
    column_to_rownames(var = "CaTCH.BC_ID")

comparison_objs <- list()
for (t in setdiff(levels(metadata$Condition), ref.Condition)) {
    print(sprintf("Processing the Condition '%s'...", t))

    contrast_name <- paste(t, ref.Condition, sep = "-vs-")
    detool <- "DESEQ2"
    if (length(metadata$Replicate) >= length(metadata$Condition) * 2) {
        print("Enough replicates found, running DESeq2")

        ddslist <- run_deseq_bcs(contrast_name, metadata, countData)
    } else {
        print("Not enough replicates found, running edgeR")
        detool <- "EDGER"
        ddslist <- run_edger_bcs(contrast_name, metadata, countData)
    }
    comparison_objs[[contrast_name]] <- ddslist

    r <- ddslist[["res"]]

    if (nrow(r) > 1) {
        write.table(as.data.frame(r), gzfile(paste("DE_", detool, "_", contrast_name, "_BCs_fdr", opt$pcut, ".tsv.gz", sep = "")), sep = "\t", row.names = FALSE, quote = F)

        pdf(
            file = paste("DE_", detool, "_", contrast_name, "_BCs_Volcano_p", opt$pcut, "_lfc", opt$fcut, ".pdf", sep = ""),
            width = 15, height = 10
        )
        print(EnhancedVolcano(r,
            lab = rownames(r),
            x = "log2FoldChange",
            y = "p.adj",
            title = paste0(contrast_name, "_p", opt$pcut, "_lfc", opt$fcut, sep = ""),
            pCutoff = opt$pcut,
            FCcutoff = opt$fcut,
            pointSize = 3.0,
            labSize = 5.0,
            colAlpha = .3,
            legendLabels = c(
                "Not sig.", "Log (base 2) FC", "p-value",
                "p-value & Log (base 2) FC"
            ),
            legendPosition = "right",
            legendLabSize = 10,
            legendIconSize = 5.0,
            drawConnectors = TRUE,
            widthConnectors = 0.75
        ))
        dev.off()
    } else {
        pdf(file = paste("DE", detool, "_", contrast_name, "BCs_Volcano", "p005_lfc15.pdf", sep = "_"), width = 15, height = 10)
        print(paste("No significantly differential Barcodes found for ", contrast_name))
        dev.off()
    }
    rm(r, ddslist)
}

saveRDS(comparison_objs, file = paste0(opt$out, "_DE_list.rds.gz"), compress = "gzip")
