.libPaths("")

library(optparse)

option_list <- list(
    make_option(c("--sce"),
        type = "character", default = NULL,
        help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"
    ),
    make_option(c("--baseCond"),
        type = "character", default = NULL,
        help = "Base condition for DE Analysis"
    ),
    make_option(c("--format"),
        type = "character", default = "pdf",
        help = "format of the plots: pdf (default), jpeg, png, tiff"
    ),
    make_option(c("--organism"),
        type = "character", default = "Human",
        help = "Organism to analyze pathways for"
    ),
    make_option(c("--width"),
        type = "numeric", default = 20,
        help = "width of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--height"),
        type = "numeric", default = 25,
        help = "height of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--pcut"),
        type = "numeric", default = 0.1,
        help = "Cutoff for pvalues, default(0.1)"
    ),
    make_option(c("--fcut"),
        type = "numeric", default = 1,
        help = "Cutoff for lFC, default(1)"
    ),
    make_option(c("--out"),
        type = "character", default = NULL,
        help = "path to the output file"
    ),
    make_option(c("--libpath"),
        type = "character", default = "/tools/scripts/R/",
        help = "path to R libs, trailing slash is required"
    )
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)) {
    print_help(opt_parser)
    stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if (!(opt$format %in% c("pdf", "png", "jpeg", "tiff"))) {
    opt$format <- "pdf"
}

#### Source Functions ####
source(paste0(opt$libpath, "singlecell_utils.R"))

########################################################
library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(Seurat)
# options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")
library(SeuratWrappers)
library(gridExtra)
library(DESeq2)
library(apeglm)
library(EnhancedVolcano)
library(sctransform)
library(R.filesets)
library(progeny)
library(dorothea)
library(decoupleR)
library(OmnipathR)
library(ComplexHeatmap)
#### Load single cell data generated by the NF pipeline ####
sce <- loadRDS(opt$sce)

if (DefaultAssay(sce) != "RNA") {
    DefaultAssay(sce) <- "RNA" # NOT "RNA_integrated.cca"
}

### set reference condition ###
ref.Condition <- opt$baseCond

# ### Change Ident
orig.ident <- Idents(sce)
Idents(sce) <- sce[[]]$pca_cluster
 
### Generate Pseudobulk ####
pseudo <- AggregateExpression(sce, assays = "RNA", return.seurat = T, group.by = c("Condition", "ident"))
 
pseudo$de.ident <- pseudo@meta.data %>% 
   dplyr::select(Condition) %>%
   mutate(Condition = as.factor(gsub("-", ".", Condition)))
Idents(pseudo) <- "de.ident"
 
# Extract Count Data
countData <- pseudo@assays$RNA$counts %>%
  as_tibble(rownames = "Gene") %>%
  rename_with(., ~ gsub("-|_", ".", ., perl = T)) %>%
  rename_with(., ~ gsub("\\.([0-9]+)", "_\\1", ., perl = T)) %>%
  column_to_rownames("Gene")

pseudo$Sample <- pseudo@meta.data %>%
   rownames_to_column(., var = "Sample") %>%
   mutate(Sample = gsub("-|_", ".", Sample, perl = T)) %>%
   mutate(Sample = gsub("\\.([0-9]+)", "_\\1", Sample, perl = T)) %>%
   pull(Sample)

ids <- countData %>%
    as_tibble(rownames = "Gene")

# Extract Metadata
metadata <- pseudo@meta.data %>%
   as_tibble(rownames = NA) %>%
   dplyr::select(Sample, Condition) %>%
   distinct() %>%
   as.data.frame()
metadata <- metadata %>%
  mutate(Condition = as.factor(gsub("-|_", ".", Condition, perl = T))) %>%
  mutate(Condition = as.factor(gsub("\\.([0-9]+)", "_\\1", Condition, perl = T)))
row.names(metadata) <- NULL

### Pseudo Gene DE #####
comparison_objs <- list()

for (t in setdiff(levels(metadata$Condition), ref.Condition)) {
  
  contrast_name <- paste(t, ref.Condition, sep = "-vs-")
  print(paste("ANALYSING ", contrast_name))
  
  detool <- "DESeq2"
  if (length(unique(metadata$Sample)) >= length(unique(metadata$Condition)) * 2) {
    print("Enough replicates found, running DESeq2")
    ddslist <- run_deseq(contrast_name, metadata, countData, ids, cooksCutoff = FALSE)
  } else {
    print("Not enough replicates found, running edgeR")
    detool <- "EdgeR"
    ddslist <- run_edger(contrast_name, metadata, countData, ids)
  }
  comparison_objs[[contrast_name]] <- ddslist
  
  deres <- ddslist[["res"]]
  
  if (nrow(deres) > 1) {
    write.table(deres, gzfile(paste("DE_", detool, contrast_name, "_GENES_all.tsv.gz", sep = "")), sep = "\t", row.names = FALSE, quote = F)
    
    pdf(
      file = paste("DE_", detool, contrast_name, "_GENES_Volcano_p", opt$pcut, "_lfc", opt$fcut, ".pdf", sep = ""),
      width = 15, height = 10
    )
    print(EnhancedVolcano(deres,
                          lab = deres$Gene,
                          x = "log2FoldChange",
                          y = "p.adj",
                          title = paste0(contrast_name, "_p", opt$pcut, "_lfc", opt$fcut, sep = ""),
                          pCutoff = opt$pcut,
                          FCcutoff = opt$fcut,
                          pointSize = 2.0,
                          labSize = 4.0,
                          colAlpha = .2,
                          xlab = bquote(~ Log[2] ~ "fold change"),
                          ylab = bquote(~ Log[10] ~ "padj"),
                          boxedLabels = TRUE,
                          # parseLabels = TRUE,
                          legendLabels = c(
                            "Not sig.", "Log (base 2) FC", "p-value",
                            "p-value & Log (base 2) FC"
                          ),
                          legendPosition = "bottom",
                          legendLabSize = 10,
                          legendIconSize = 8.0,
                          drawConnectors = TRUE,
                          widthConnectors = 0.25
    ) + coord_flip())
    dev.off()
  }
}

saveRDS(comparison_objs, file = paste0(opt$out, "_DE_pseudobulk_list.rds.gz"), compress = "gzip")

### Run pathway enrichment (https://www.bioconductor.org/packages/release/bioc/vignettes/decoupleR/inst/doc/pw_sc.html)
print(paste0("Retrieving target genes for pathways in ", opt$organism))
net <- get_progeny(organism = opt$organism)

### Pathway analysis
# Extract the normalized log-transformed counts, WE FILTER HERE ONLY FOR LFC!!!
print("Normalizing pseudo bulk")
pseudo <- NormalizeData(pseudo) %>%
    FindVariableFeatures() %>%
    ScaleData() %>%
    RunPCA(npcs = 10)
Idents(pseudo) <- "Condition"
# Join normalized count layers for DE analysis
# print("Joining Layers")
# pseudo <- join_SCE(pseudo)

# Extract the normalized log-transformed counts
print("Extracting counts")
mat <- LayerData(pseudo, assay = "RNA", layer = "data")

# Run wmean
print("Wmean analysis")
acts <- run_wmean(
    mat = mat, net = net, .source = "source", .target = "target",
    .mor = "weight", times = 100, minsize = 5
)

rm(mat)

# Extract activities from object as a long dataframe
print("Extracting activities")

df <- t(as.matrix(acts %>%
    filter(statistic == "norm_wmean") %>%
    pivot_wider(
        id_cols = "source", names_from = "condition",
        values_from = "score"
    ) %>%
    column_to_rownames("source"))) %>%
    as.data.frame() %>%
    mutate(cluster = Idents(pseudo)) %>%
    pivot_longer(cols = -cluster, names_to = "source", values_to = "score") %>%
    group_by(cluster, source) %>%
    summarise(mean = mean(score))

# Transform to wide matrix
top_acts_mat <- df %>%
    pivot_wider(
        id_cols = "cluster", names_from = "source",
        values_from = "mean"
    ) %>%
    column_to_rownames("cluster") %>%
    as.matrix()

# Plot
print("Plotting")
pdf(
    file = paste("DE_", "Seurat_Pathway_Heatmap.pdf", sep = ""),
    width = 15, height = 10
)
print(Heatmap(top_acts_mat))
dev.off()

# Reset Idents
Idents(sce) <- orig.ident

