.libPaths("")

library(optparse)

option_list <- list(
    make_option(c("--sce"),
        type = "character", default = NULL,
        help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"
    ),
    make_option(c("--baseCond"),
        type = "character", default = NULL,
        help = "Base condition for DE Analysis"
    ),
    make_option(c("--format"),
        type = "character", default = "pdf",
        help = "format of the plots: pdf (default), jpeg, png, tiff"
    ),
    make_option(c("--organism"),
        type = "character", default = "human",
        help = "Organism to analyze pathways for"
    ),
    make_option(c("--width"),
        type = "numeric", default = 20,
        help = "width of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--height"),
        type = "numeric", default = 25,
        help = "height of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
    ),
    make_option(c("--pcut"),
        type = "numeric", default = 0.1,
        help = "Cutoff for pvalues, default(0.1)"
    ),
    make_option(c("--fcut"),
        type = "numeric", default = 1,
        help = "Cutoff for lFC, default(1)"
    ),
    make_option(c("--out"),
        type = "character", default = NULL,
        help = "path to the output file"
    )
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)) {
    print_help(opt_parser)
    stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if (!(opt$format %in% c("pdf", "png", "jpeg", "tiff"))) {
    opt$format <- "pdf"
}


##### Additional methods #####
# Join for DE
join_SCE <- function(sce, assay = "RNA", layers = "data", new = "joined") {
    print("   Joining SCE layers  ...")

    sce <- JoinLayers(sce, assay = assay, layers = layers, new = new)
    return(sce)
}

########################################################
library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(Seurat)
# options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")
library(SeuratWrappers)
library(gridExtra)
library(DESeq2)
library(apeglm)
library(EnhancedVolcano)
library(sctransform)
library(R.filesets)
library(progeny)
library(dorothea)
library(decoupleR)
library(ComplexHeatmap)
#### Load single cell data generated by the NF pipeline ####
sce <- loadRDS(opt$sce)

if (DefaultAssay(sce) != "RNA") {
    DefaultAssay(sce) <- "RNA" # NOT "RNA_integrated.cca"
}
#### Use DeSeq2 to identify over- and underrepresented barcodes ####

### We want days as "Condition" ### need to add that

sce$Condition <- as.factor(unlist(lapply(sce$Sample, function(x) str_split_1(x, "_")[1])))
sce$Replicate <- as.factor(unlist(lapply(sce$Sample, function(x) paste(unlist(str_split_1(x, "_"))[-1], collapse = "-"))))
# sce$Replicate <- as.factor(unlist(lapply(sce$Sample, function(x) str_split_1(x, "_")[2])))

### set reference condition ###
ref.Condition <- opt$baseCond

### Generate Pseudobulk ###
pseudo <- AggregateExpression(sce, assays = "RNA", return.seurat = T, group.by = c("ident", "Condition", "Replicate"))
# each 'cell' is a donor-condition-celltype pseudobulk profile
# tail(Cells(pseudo))

# pseudo$de.ident <- paste(pseudo$Condition, pseudo$Replicate, sep = "_")
pseudo$de.ident <- pseudo$Condition
Idents(pseudo) <- "de.ident"

reslist <- list()
for (t in setdiff(levels(sce$Condition), ref.Condition)) {
    print(sprintf("Processing the Condition '%s'...", t))

    contrast_name <- paste(t, ref.Condition, sep = "-vs-")
    test <- "DESeq2"
    tryCatch(
        {
            deres <- FindMarkers(
                object = pseudo,
                ident.1 = t,
                ident.2 = ref.Condition,
                test.use = "DESeq2"
            )
        },
        error = function(e) {
            test <- "Wilcox"
            deres <- FindMarkers(
                object = pseudo,
                ident.1 = t,
                ident.2 = ref.Condition,
                test.use = "wilcox"
            )
        }
    )
    reslist[[contrast_name]] <- deres
    write.table(deres, gzfile(paste("DE_", "Seurat_", test, contrast_name, "_GENES_all.tsv.gz", sep = "")), sep = "\t", row.names = FALSE, quote = F)

    pdf(
        file = paste("DE_", "Seurat_", test, contrast_name, "_GENES_Volcano_p", opt$pcut, "_lfc", opt$fcut, ".pdf", sep = ""),
        width = 15, height = 10
    )
    print(EnhancedVolcano(deres,
        lab = rownames(deres),
        x = "avg_log2FC",
        y = "p_val_adj",
        title = paste0(contrast_name, "_p", opt$pcut, "_lfc", opt$fcut, sep = ""),
        pCutoff = opt$pcut,
        FCcutoff = opt$fcut,
        pointSize = 2.0,
        labSize = 4.0,
        colAlpha = .2,
        xlab = bquote(~ Log[2] ~ "fold change"),
        boxedLabels = TRUE,
        # parseLabels = TRUE,
        legendLabels = c(
            "Not sig.", "Log (base 2) FC", "p-value",
            "p-value & Log (base 2) FC"
        ),
        legendPosition = "bottom",
        legendLabSize = 10,
        legendIconSize = 8.0,
        drawConnectors = TRUE,
        widthConnectors = 0.25
    ) + coord_flip())
    dev.off()


    # counts <- pseudo %>% filter(avg_log2FC >= opt$fcut) %>% dplyr::rename(!!t := pct.1, !!ref.Condition := pct.2) %>% select(all_of(c(t#, ref.Condition))) %>%
    #    dplyr::mutate_if(~ any(is.na(.x)), ~ if_else(is.na(.x),0,.x)) %>%
    #    as.matrix()
    #
    ## Run wmean
    # acts <- run_wmean(mat=counts, net=net, .source='source', .target='target',
    #                  .mor='weight', times = 100, minsize = 5)
    #
    ## Transform to wide matrix
    # acts_mat <- acts %>%
    #    filter(statistic == 'norm_wmean') %>%
    #    pivot_wider(id_cols = 'condition', names_from = 'source',
    #                values_from = 'score') %>%
    #    column_to_rownames('condition') %>%
    #    as.matrix()
    #
    ## Scale per sample
    # acts_mat <- scale(acts_mat)
    #
    ## Choose color palette
    # palette_length = 100
    # my_color = colorRampPalette(c("Darkblue", "white","red"))(palette_length)
    #
    # my_breaks <- c(seq(-3, 0, length.out=ceiling(palette_length/2) + 1),
    #               seq(0.05, 3, length.out=floor(palette_length/2)))
    #
    ## Plot
    # pdf(
    #    file = paste("DE_", "Seurat_", contrast_name, "_Pathway_Heatmap_nop_lfc", opt$fcut, ".pdf", sep = ""),
    #    width = 15, height = 10
    # )
    # print(heatmap(acts_mat, border_color = NA, color=my_color, breaks = my_breaks))
    # dev.off()
}

saveRDS(reslist, file = paste0(opt$out, "_DE_pseudobulk_list.rds.gz"), compress = "gzip")

### Run pathway enrichment (https://www.bioconductor.org/packages/release/bioc/vignettes/decoupleR/inst/doc/pw_sc.html)
print(paste0("Retrieving target genes for pathways in ", opt$species))
net <- get_progeny(organism = opt$species)

### Pathway analysis
# Extract the normalized log-transformed counts, WE FILTER HERE ONLY FOR LFC!!!
pseudo <- NormalizeData(pseudo) %>%
    FindVariableFeatures() %>%
    ScaleData() %>%
    RunPCA(npcs = 10)

#### Same Pathway analysis on single-cell level

# Join normalized count layers for DE analysis
Idents(pseudo) <- "Condition"

# Extract the normalized log-transformed counts
mat <- LayerData(pseudo, assay = "RNA", layer = "data")

# Run wmean
acts <- run_wmean(
    mat = mat, net = net, .source = "source", .target = "target",
    .mor = "weight", times = 100, minsize = 5
)

rm(mat)
# Extract norm_wmean and store it as pwm layer in sce
#
LayerData(pseudo, assay = "RNA", layer = "pwm") <- acts %>%
    filter(statistic == "norm_wmean") %>%
    pivot_wider(
        id_cols = "source", names_from = "condition",
        values_from = "score"
    ) %>%
    column_to_rownames("source") %>%
    CreateAssay5Object(.)

rm(acts)

# Extract activities from object as a long dataframe
df <- t(as.matrix(LayerData(pseudo, assay = "RNA", layer = "pwm"))) %>%
    as.data.frame() %>%
    mutate(cluster = Idents(pseudo)) %>%
    pivot_longer(cols = -cluster, names_to = "source", values_to = "score") %>%
    group_by(cluster, source) %>%
    summarise(mean = mean(score))

df <- t(as.matrix(acts %>%
    filter(statistic == "norm_wmean") %>%
    pivot_wider(
        id_cols = "source", names_from = "condition",
        values_from = "score"
    ) %>%
    column_to_rownames("source"))) %>%
    as.data.frame() %>%
    mutate(cluster = Idents(pseudo)) %>%
    pivot_longer(cols = -cluster, names_to = "source", values_to = "score") %>%
    group_by(cluster, source) %>%
    summarise(mean = mean(score))

# Transform to wide matrix
top_acts_mat <- df %>%
    pivot_wider(
        id_cols = "cluster", names_from = "source",
        values_from = "mean"
    ) %>%
    column_to_rownames("cluster") %>%
    as.matrix()

# Choose color palette
palette_length <- 100
my_color <- colorRampPalette(c("Darkblue", "white", "red"))(palette_length)

my_breaks <- c(
    seq(-2, 0, length.out = ceiling(palette_length / 2) + 1),
    seq(0.05, 2, length.out = floor(palette_length / 2))
)

# Plot
pdf(
    file = paste("DE_", "Seurat_", contrast_name, "_Pathway_Heatmap_nop_lfc", opt$fcut, ".pdf", sep = ""),
    width = 15, height = 10
)
print(Heatmap(top_acts_mat))
dev.off()