.libPaths("")

library(optparse)

option_list = list(
  make_option(c("--sce"), type="character", default = NULL, 
              help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"),
  make_option(c("--plots_per_row"), type="numeric", default = 5, 
              help = "number of barcode plots per row of the output plot"),
  make_option(c("--format"), type="character", default = "pdf", 
              help = "format of the plots: pdf (default), jpeg, png, tiff"),
  make_option(c("--width"), type="numeric", default = 4, 
              help = "width of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"),
  make_option(c("--height"), type = "numeric", default = 3, 
              help = "height of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"),
  make_option(c("--outdir"), type="character", default = NULL, 
              help = "output directory")
)

opt_parser = OptionParser(option_list = option_list)
opt = parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)){
  print_help(opt_parser)
  stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if (!(opt$format %in% c("pdf", "png", "jpeg", "tiff"))) {
  opt$format <- "pdf"
}


##### Additional methods #####
activity_by_logmeans <- function(signature, sce, fn.scale = scale, ...) {
  # check if logcounts is present
  stopifnot("logcounts" %in% names(assays(sce)))
  
  # determine shared features between sce and signature
  shared_features <- intersect(signature, rownames(sce))
  stopifnot(length(shared_features) > 0)
  
  # calculate scaled log-means of signature
  return (sce[shared_features, ] %>%
            assay("logcounts") %>%
            Matrix::colMeans() %>%
            # use scale by default, but allow other functions and additional arguments
            fn.scale(...) %>%
            as.numeric())
}

assignMarkerScore <- function(sce, markers = NULL, col.name = NULL, fn.scale = NULL, ...) {
  
  if (is.null(sce)) {
    stop("'sce' must be specified and cannot be NULL")
  }
  if (is.null(markers)) {
    stop("'markers' must be specified and cannot be NULL")
  }
  if (is.null(col.name)) {
    stop("'col.name' must be specified and cannot be NULL")
  }
  
  if (is.null(fn.scale)) {
    scores <- map_df(list("markers" = markers), activity_by_logmeans, sce = sce) %>%
      scale()
  } else {
    scores <- map_df(list("markers" = markers), activity_by_logmeans, sce = sce, fn.scale = fn.scale, ...)
  }
  
  colData(sce)[col.name] <- scores
  return (sce)
}

generatePaletteColors <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}


########################################################
library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(gridExtra)
library(DESeq2)


#### Load single cell data generated by the NF pipeline ####
load(opt$sce)
#load("/data/gcbds/users/nowoshil/Projects/CaTCH2.0/KRASi_ON_vs_OFF/Exp1010/_NF_run_/outputs/sce/sce.rda")
#rm(sce.unfiltered)


#### Use DeSeq2 to identify over- and underrepresented barcodes ####
metadata <- colData(sce) %>% 
            as_tibble() %>% 
            select(Sample, Treatment) %>% 
            distinct()
ref.treatment <- levels(metadata$Treatment)[1]

bc.counts <- colData(sce) %>% 
             as_tibble() %>%
             filter(CaTCH.Status == "Singlet") %>%
             select(CaTCH.BCs, Sample, BC_ID) %>%
             group_by(CaTCH.BCs, Sample) %>%
             mutate(n = n()) %>%
             ungroup() %>%
             distinct() %>%
             pivot_wider(names_from = Sample, values_from = n, values_fill = 0) %>%
             filter(rowSums(across(starts_with(ref.treatment))) > 0)

idx <- match(metadata$Sample, setdiff(colnames(bc.counts), c("CaTCH.BCs", "BC_ID")))
metadata <- metadata[idx, ]

dds <- DESeqDataSetFromMatrix(countData = bc.counts %>%
                                          select(-CaTCH.BCs) %>%
                                          column_to_rownames(var = "BC_ID"),
                              colData = metadata,
                              design= ~ Treatment)
dds <- DESeq(dds)


#### Generate plots ####
cs.color <- list("G0" = "darkblue",
                 "G1S" = "#FDB916",
                 "G2M" = "#11B09C",
                 "M" = "#D22248",
                 "MG1" = "#F17724",
                 "S" = "#BECE2D")
cs.color.ex <- cs.color
cs.color.ex[["Another barcode"]] = "grey85"

points <- reducedDim(sce, type = "TSNE") %>%
          as_tibble(rownames = "CellID") %>%
          plyr::rename(replace = c("V1" = "X", "V2" = "Y")) 
points$CellStage <- sce$CellStage
points$CaTCH.BCs <- sce$CaTCH.BCs
points$Cluster <- sce$Cluster
points$Treatment <- sce$Treatment
common.bcs <- c()
for (t in setdiff(levels(metadata$Treatment), ref.treatment)) {
  print(sprintf("Processing the treatment '%s'...", t))
  r <- results(dds, 
               alpha = 0.05,
               contrast = c("Treatment", t, ref.treatment)) %>%
       as_tibble(rownames = NA) %>% 
       rownames_to_column("BC_ID") %>%
       filter(!is.na(padj), padj <= 0.05) %>%
       mutate(Type = if_else(log2FoldChange > 0, "Enriched", "Depleted")) %>%
       arrange(desc(Type), desc(abs(log2FoldChange)))
  
  print("   Plotting the over- and underrepresented CaTCH barcodes...")
  plots <- list()
  for (i in 1:nrow(r)) {
    bc.id <- r$BC_ID[i]
    bc <- bc.counts$CaTCH.BCs[which(bc.counts$BC_ID == bc.id)]
    common.bcs <- c(common.bcs, bc.id)
    
    tmp <- bc.counts %>%
           filter(CaTCH.BCs == bc) %>%
           select(starts_with(c(ref.treatment, t))) %>%
           mutate(MeanRef = rowMeans(across(starts_with(ref.treatment))),
                  MeanTreatment = rowMeans(across(starts_with(t)))) %>%
           select(MeanRef, MeanTreatment) %>%
           as.matrix()
    p <- points %>%
         mutate(Highlight = if_else(CaTCH.BCs == bc & Treatment %in% c(t, ref.treatment), CellStage, "Another barcode")) %>%
         arrange(Highlight) %>%
         ggplot(aes(x = X, y = Y, color = Highlight)) + 
          geom_point() + 
          scale_color_manual(values = cs.color.ex, na.value = "white") +
          #ggtitle(sprintf("Barcode %s. log2FC: %.1f (%d vs %d)", bc.id, r$log2FoldChange[i], round(tmp[1]), round(tmp[2]))) + 
          xlab("tSNE1") + 
          ylab("tSNE2") + 
          theme(legend.position = "none")
    plots[[length(plots) + 1]] <- p
    
    p <- points %>%
         filter(CaTCH.BCs == bc, Treatment %in% c(t, ref.treatment)) %>%
         ggplot(aes(x = Cluster, fill = CellStage)) + 
          geom_bar() + 
          scale_fill_manual(values = cs.color, name = "Cell cycle stage") + 
          ylab("Cell count")
    plots[[length(plots) + 1]] <- p
    
  }
  
  print("   Saving the plots...")
  nPlotsPerRow = opt$plots_per_row * 2
  jpeg(filename = paste0(opt$outdir, "/", t, ".jpeg"), 
       width = nPlotsPerRow * opt$width, 
       height = ceiling(length(plots) / nPlotsPerRow) * opt$height)
  do.call("grid.arrange", c(plots, ncol = nPlotsPerRow))
  dev.off()
}
  

bc.stats <- tibble(BC_ID = common.bcs) %>%
            group_by(BC_ID) %>%
            mutate(Count = n()) %>%
            ungroup() %>%
            filter(Count == length(levels(metadata$Treatment)) - 1) %>%
            distinct()

t.colors <- generatePaletteColors(length(levels(metadata$Treatment)) + 1)
names(t.colors) <- c(levels(metadata$Treatment), " Another barcode")
t.colors[" Another barcode"] <- "grey85"
plots <- list()
for (i in 1:nrow(bc.stats)) {
  bc.id <- bc.stats$BC_ID[i]
  bc <- bc.counts$CaTCH.BCs[which(bc.counts$BC_ID == bc.id)]
  p <- points %>%
       mutate(Highlight = if_else(CaTCH.BCs == bc, as.character(Treatment), " Another barcode")) %>%
       arrange(Highlight) %>%
       ggplot(aes(x = X, y = Y, color = Highlight)) + 
        geom_point() + 
        scale_color_manual(values = t.colors, name = "Treatment", na.value = "white") +
        ggtitle(sprintf("Barcode %s", bc.id)) + 
        xlab("tSNE1") + 
        ylab("tSNE2")
  plots[[length(plots) + 1]] <- p
}
jpeg(filename = paste0(opt$outdir, "/common.jpeg"), 
     width = opt$plots_per_row * opt$width, 
     height = ceiling(length(plots) / opt$plots_per_row) * opt$height)
do.call("grid.arrange", c(plots, ncol = opt$plots_per_row))
dev.off()
