.libPaths("")

library(optparse)

option_list <- list(
  make_option(c("--sce"),
    type = "character", default = NULL,
    help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"
  ),
  make_option(c("--baseCond"),
    type = "character", default = NULL,
    help = "Base condition for DE Analysis"
  ),
  make_option(c("--plots_per_row"),
    type = "numeric", default = 5,
    help = "number of barcode plots per row of the output plot"
  ),
  make_option(c("--format"),
    type = "character", default = "pdf",
    help = "format of the plots: pdf (default), jpeg, png, tiff"
  ),
  make_option(c("--width"),
    type = "numeric", default = 20,
    help = "width of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
  ),
  make_option(c("--height"),
    type = "numeric", default = 25,
    help = "height of the plot of a single CaTCH barcode. The units depend on the format: inches for PDF, pixels otherwise"
  ),
  make_option(c("--outdir"),
    type = "character", default = NULL,
    help = "output directory"
  )
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)) {
  print_help(opt_parser)
  stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if (!(opt$format %in% c("pdf", "png", "jpeg", "tiff"))) {
  opt$format <- "pdf"
}


##### Additional methods #####
activity_by_logmeans <- function(signature, sce, fn.scale = scale, ...) {
  # check if logcounts is present
  stopifnot("logcounts" %in% names(assays(sce)))

  # determine shared features between sce and signature
  shared_features <- intersect(signature, rownames(sce))
  stopifnot(length(shared_features) > 0)

  # calculate scaled log-means of signature
  return(sce[shared_features, ] %>%
    assay("logcounts") %>%
    Matrix::colMeans() %>%
    # use scale by default, but allow other functions and additional arguments
    fn.scale(...) %>%
    as.numeric())
}

assignMarkerScore <- function(sce, markers = NULL, col.name = NULL, fn.scale = NULL, ...) {
  if (is.null(sce)) {
    stop("'sce' must be specified and cannot be NULL")
  }
  if (is.null(markers)) {
    stop("'markers' must be specified and cannot be NULL")
  }
  if (is.null(col.name)) {
    stop("'col.name' must be specified and cannot be NULL")
  }

  if (is.null(fn.scale)) {
    scores <- map_df(list("markers" = markers), activity_by_logmeans, sce = sce) %>%
      scale()
  } else {
    scores <- map_df(list("markers" = markers), activity_by_logmeans, sce = sce, fn.scale = fn.scale, ...)
  }

  colData(sce)[col.name] <- scores
  return(sce)
}

generatePaletteColors <- function(n) {
  hues <- seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}


run_deseq <- function(contrast, sampleData_all, countData_all, ids) {
  contrast_name <- contrast
  contrast_groups <- strsplit(contrast, "-vs-")
  print(paste("Comparing ", contrast_name, sep = ""))

  # determine contrast
  A <- unlist(strsplit(contrast_groups[[1]][1], "\\+"), use.names = FALSE)
  B <- unlist(strsplit(contrast_groups[[1]][2], "\\+"), use.names = FALSE)

  # subset Datasets for pairwise comparison
  countData <- cbind(countData_all[, grepl(paste("^", B, "_", sep = ""), colnames(countData_all))], countData_all[, grepl(paste("^", A, "_", sep = ""), colnames(countData_all))])
  sampleData <- droplevels(rbind(subset(sampleData_all, B == Condition), subset(sampleData_all, A == Condition)))

  sampleData <- sampleData %>% add_column(type = "none")
  sampleData <- sampleData %>% add_column(batch = "none")

  ## Create design-table considering different types (paired, unpaired) and batches
  if (length(unique(subset(sampleData, A == Condition)$type)) > 1 | length(unique(subset(sampleData, B == Condition)$type)) > 1) {
    if (length(unique(subset(sampleData, A == Condition)$batch)) > 1 | length(unique(subset(sampleData, B == Condition)$batch)) > 1) {
      design <- ~ type + batch + Condition
    } else {
      design <- ~ type + Condition
    }
  } else {
    if (length(unique(subset(sampleData, A == Condition)$batch)) > 1 | length(unique(subset(sampleData, B == Condition)$batch)) > 1) {
      design <- ~ batch + Condition
    } else {
      design <- ~Condition
    }
  }
  print(design)

  # Create DESeqDataSet
  dds <- DESeqDataSetFromMatrix(countData = countData, colData = sampleData, design = design)

  # filter low counts
  # keep <- rowSums(counts(dds)) >= 10
  # dds <- dds[keep, ]

  # drop unused samples
  dds$Condition <- droplevels(dds$Condition)

  # relevel to base condition B
  dds$Condition <- relevel(dds$Condition, ref = B[[1]])

  # run for each pair of conditions
  dds <- tryCatch(
    {
      DESeq(dds, parallel = FALSE, betaPrior = FALSE)
    },
    error = function(e) {
      dds <- estimateSizeFactors(dds)
      dds <- estimateDispersionsGeneEst(dds)
      dispersions(dds) <- mcols(dds)$dispGeneEst
      return(nbinomWaldTest(dds))
    }
  )
  print(resultsNames(dds))

  # Now we want to transform the raw discretely distributed counts so that we can do clustering. (Note: when you expect a large treatment effect you should actually set blind=FALSE (see https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html).

  rld <- rlogTransformation(dds, blind = TRUE)
  vsd <- varianceStabilizingTransformation(dds, blind = TRUE)

  # We also write the normalized counts to file
  write.table(as.data.frame(assay(rld)), gzfile(paste("DE", "DESEQ2", contrast_name, "table", "rld.tsv.gz", sep = "_")), sep = "\t", col.names = NA)
  write.table(as.data.frame(assay(vsd)), gzfile(paste("DE", "DESEQ2", contrast_name, "table", "vsd.tsv.gz", sep = "_")), sep = "\t", col.names = NA)

  # initialize empty objects
  res <- ""
  resOrdered <- ""
  res <- results(dds, contrast = c("Condition", A, B), parallel = TRUE)
  resn <- res
  res_shrink <- lfcShrink(dds = dds, coef = paste("Condition", A, "vs", B, sep = "_"), res = res, type = "apeglm")

  res_shrink <- left_join(res_shrink %>%
    as_tibble(rownames = NA) %>%
    rownames_to_column("BC_ID"), ids, by = "BC_ID")

  # sort and output
  resOrdered <- res_shrink[order(res_shrink$log2FoldChange), ]

  # write the table to a tsv file
  write.table(as.data.frame(resOrdered), gzfile(paste("DE", "DESEQ2", contrast_name, "table", "results.tsv.gz", sep = "_")), sep = "\t", row.names = FALSE, quote = F)

  # Output no shrink
  res <- resn[order(resn$log2FoldChange), ]
  res <- left_join(res %>%
    as_tibble(rownames = NA) %>%
    rownames_to_column("BC_ID"), ids, by = "BC_ID")

  write.table(as.data.frame(res), gzfile(paste("DE", "DESEQ2", contrast_name, "table", "results_noshrink.tsv.gz", sep = "_")), sep = "\t", row.names = FALSE, quote = F)
  rm(res, resn, resOrdered)
  return(list(dds = dds, res = res_shrink))
}

########################################################
library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(Seurat)
# options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")
library(SeuratWrappers)
library(gridExtra)
library(DESeq2)
library(apeglm)
library(EnhancedVolcano)
library(sctransform)
library(R.filesets)

#### Load single cell data generated by the NF pipeline ####
sce <- loadRDS(opt$sce)

if (DefaultAssay(sce) != "RNA_integrated.cca") {
  DefaultAssay(sce) <- "RNA_integrated.cca" # DefaultAssay(sce) <- "RNA_integrated.cca"
}
#### Use DeSeq2 to identify over- and underrepresented barcodes ####

### We want days as "Condition" ### need to add that

sce$Condition <- as.factor(unlist(lapply(sce$Sample, function(x) str_split_1(x, "_")[1])))
sce$Replicate <- as.factor(unlist(lapply(sce$Sample, function(x) str_split_1(x, "_")[2])))

### collect metadata ###
metadata <- sce@meta.data %>%
  select(Sample, Condition) %>%
  distinct()

### set reference condition ###
ref.Condition <- opt$baseCond

### Add Barcode IDS ###
if (!("BC_ID" %in% colnames(sce@meta.data))) {
  tmp <- sce@meta.data %>%
    select(c(CaTCH.Status, Condition, CaTCH.BCs, Sample)) %>%
    filter(CaTCH.Status == "Singlet", Condition == ref.Condition) %>%
    select(CaTCH.BCs, Sample) %>%
    group_by(CaTCH.BCs, Sample) %>%
    mutate(n = n()) %>%
    ungroup() %>%
    distinct() %>%
    pivot_wider(names_from = Sample, values_from = n, values_fill = 0) %>%
    filter(rowSums(across(starts_with(ref.Condition))) > 0) %>%
    mutate(.Means = rowMeans(across(starts_with(ref.Condition)))) %>%
    arrange(by = desc(.Means)) %>%
    rowid_to_column(".ID") %>%
    mutate(BC_ID = paste0("BC_", .ID)) %>%
    select(-.Means, -.ID) %>%
    relocate(BC_ID, .after = CaTCH.BCs) %>%
    select(CaTCH.BCs, BC_ID)

  sce@meta.data$BC_ID <- sce@meta.data %>%
    left_join(y = tmp, by = "CaTCH.BCs") %>%
    mutate(BC_ID = factor(BC_ID, levels = str_sort(unique(BC_ID), numeric = TRUE))) %>%
    pull(BC_ID)
}


### Count Barcodes ###
bc.counts <- sce@meta.data %>%
  filter(CaTCH.Status == "Singlet") %>%
  select(CaTCH.BCs, Sample, BC_ID) %>%
  group_by(CaTCH.BCs, Sample) %>%
  mutate(n = n()) %>%
  ungroup() %>%
  distinct() %>%
  pivot_wider(names_from = Sample, values_from = n, values_fill = 0) %>%
  filter(rowSums(across(starts_with(ref.Condition))) > 0) %>%
  drop_na()


### Select metadata ###
idx <- match(metadata$Sample, setdiff(colnames(bc.counts), c("CaTCH.BCs", "BC_ID")))
metadata <- metadata[idx, ]
row.names(metadata) <- NULL

### Run pairwise DE Analysis for BCs ###
countData <- bc.counts %>%
  select(-CaTCH.BCs) %>%
  column_to_rownames(var = "BC_ID")

ids <- bc.counts %>%
  select(CaTCH.BCs, BC_ID)

comparison_objs <- list()
for (t in setdiff(levels(metadata$Condition), ref.Condition)) {
  print(sprintf("Processing the Condition '%s'...", t))

  contrast_name <- paste(t, ref.Condition, sep = "-vs-")
  ddslist <- run_deseq(contrast_name, metadata, countData, ids)
  comparison_objs[[contrast_name]] <- ddslist

  r <- results(ddslist[["dds"]],
    alpha = 0.05,
    contrast = c("Condition", t, ref.Condition)
  ) %>%
    as_tibble(rownames = NA) %>%
    rownames_to_column("BC_ID") %>%
    filter(!is.na(padj), padj <= 0.05) %>%
    mutate(Type = if_else(log2FoldChange > 0, "Enriched", "Depleted")) %>%
    arrange(desc(Type), desc(abs(log2FoldChange)))

  if (nrow(r) > 1) {
    r <- left_join(r, ids)

    write.table(as.data.frame(r), gzfile(paste("DE", "DESEQ2", contrast_name, "BCs", "fdr005.tsv.gz", sep = "_")), sep = "\t", row.names = FALSE, quote = F)

    pdf(
      file = paste("DE", "DESEQ2", contrast_name, "BCs_Volcano", "p005_lfc15.pdf", sep = "_"),
      width = 15, height = 10
    )
    print(EnhancedVolcano(ddslist[["res"]],
      lab = rownames(ddslist[["res"]]),
      x = "log2FoldChange",
      y = "pvalue",
      title = paste0(contrast_name, "p0.05", "lfc1.5", sep = "_"),
      pCutoff = 0.05,
      FCcutoff = 1.5,
      pointSize = 3.0,
      labSize = 5.0,
      colAlpha = .3,
      legendLabels = c(
        "Not sig.", "Log (base 2) FC", "p-value",
        "p-value & Log (base 2) FC"
      ),
      legendPosition = "right",
      legendLabSize = 10,
      legendIconSize = 5.0
    ))
    dev.off()
  } else {
    print(paste("No significantly differential Barcodes found for ", contrast_name))
  }
  rm(r, ddslist)
}

saveRDS(comparison_objs, file = paste0(opt$out, "DE_list.rds.gz"), compress = "gzip")
rm(comparison_objs)

# print("   Plotting the over- and underrepresented CaTCH barcodes...")
# plots <- list()
# for (i in 1:nrow(r)) {
#    bc.id <- r$BC_ID[i]
#    bc <- bc.counts$CaTCH.BCs[which(bc.counts$BC_ID == bc.id)]
#    common.bcs <- c(common.bcs, bc.id)

# tmp <- bc.counts %>%
#       filter(CaTCH.BCs == bc) %>%
#       select(starts_with(c(ref.Condition, t))) %>%
#       mutate(MeanRef = rowMeans(across(starts_with(ref.Condition))),
#              MeanCondition = rowMeans(across(starts_with(t)))) %>%
#       select(MeanRef, MeanCondition) %>%
#       as.matrix()
# p <- points %>%
#     mutate(Highlight = if_else(CaTCH.BCs == bc & Condition %in% c(t, ref.Condition), CellStage, "Another barcode")) %>%
#     arrange(Highlight) %>%
#     ggplot(aes(x = X, y = Y, color = Highlight)) +
#      geom_point() +
#      scale_color_manual(values = cs.color.ex, na.value = "white") +
#      #ggtitle(sprintf("Barcode %s. log2FC: %.1f (%d vs %d)", bc.id, r$log2FoldChange[i], round(tmp[1]), round(tmp[2]))) +
#      xlab("tSNE1") +
#      ylab("tSNE2") +
#      theme(legend.position = "none")
# plots[[length(plots) + 1]] <- p
#
# p <- points %>%
#     filter(CaTCH.BCs == bc, Condition %in% c(t, ref.Condition)) %>%
#     ggplot(aes(x = Cluster, fill = CellStage)) +
#      geom_bar() +
#      scale_fill_manual(values = cs.color, name = "Cell cycle stage") +
#      ylab("Cell count")
# plots[[length(plots) + 1]] <- p

# }

# print("   Saving the plots...")
# nPlotsPerRow = opt$plots_per_row * 2
# jpeg(filename = paste0(opt$outdir, "/DE_DESEQ2_", t, "_BCs.jpeg"),
#   width = nPlotsPerRow * opt$width,
#   height = ceiling(length(plots) / nPlotsPerRow) * opt$height)
# do.call("grid.arrange", c(plots, ncol = nPlotsPerRow))
# dev.off()
# }


# bc.stats <- tibble(BC_ID = common.bcs) %>%
#            group_by(BC_ID) %>%
#            mutate(Count = n()) %>%
#            ungroup() %>%
#            filter(Count == length(levels(metadata$Condition)) - 1) %>%
#            distinct()
#
# t.colors <- generatePaletteColors(length(levels(metadata$Condition)) + 1)
# names(t.colors) <- c(levels(metadata$Condition), " Another barcode")
# t.colors[" Another barcode"] <- "grey85"
# plots <- list()
# for (i in 1:nrow(bc.stats)) {
#  bc.id <- bc.stats$BC_ID[i]
#  bc <- bc.counts$CaTCH.BCs[which(bc.counts$BC_ID == bc.id)]
#  p <- points %>%
#       mutate(Highlight = if_else(CaTCH.BCs == bc, as.character(Condition), " Another barcode")) %>%
#       arrange(Highlight) %>%
#       ggplot(aes(x = X, y = Y, color = Highlight)) +
#        geom_point() +
#        scale_color_manual(values = t.colors, name = "Condition", na.value = "white") +
#        ggtitle(sprintf("Barcode %s", bc.id)) +
#        xlab("tSNE1") +
#        ylab("tSNE2")
#  plots[[length(plots) + 1]] <- p
# }
# jpeg(filename = paste0(opt$outdir, "/common.jpeg"),
#     width = opt$plots_per_row * opt$width,
#     height = ceiling(length(plots) / opt$plots_per_row) * opt$height)
# do.call("grid.arrange", c(plots, ncol = opt$plots_per_row))
# dev.off()
