.libPaths("")

library(optparse)

option_list <- list(
    make_option(c("--sce"),
        type = "character", default = NULL,
        help = "comma separated list of the SingleCellExperiment files generated by 'preprocessData.R'"
    ),
    make_option(c("--baseCond"),
        type = "character", default = NULL,
        help = "Base condition for DE Analysis"
    ),
    make_option(c("--out"),
        type = "character", default = NULL,
        help = "prefix for the output files"
    ),
    make_option(c("--libpath"),
        type = "character", default = "/tools/scripts/R/",
        help = "path to R libs, trailing slash is required"
    )
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out) || is.null(opt$baseCond)) {
    print_help(opt_parser)
    stop("Not enough parameters")
}

#### Source Functions ####
source(paste0(opt$libpath, "singlecell_utils.R"))

########################################################
library(tidyverse)
library(SingleCellExperiment)
library(Seurat)
options(Seurat.object.assay.version = "v5")
library(R.filesets)

#### Prepare barbieQ input from the CaTCH barcode counts ####
# The barcode counts are taken from the cell metadata of ALL SCE files of this
# sample tag, so the count matrix covers every condition and replicate.
cellmeta <- collect_SCE_metadata(opt$sce)

### set reference condition ###
ref.Condition <- opt$baseCond

# Check if reference condition is present in the metadata
if (!ref.Condition %in% as.character(cellmeta$Condition)) {
    writeLines(
        paste0("SKIPPED differential enrichment: reference condition '", ref.Condition, "' not found in the metadata"),
        paste0(opt$out, "_barbieQ_status.txt")
    )
    stop("Reference condition not found in the metadata")
}

# CaTCH.BC_ID is ranked for the whole run by 'assign_barcode_ids.R'. It is only
# rebuilt here when the provided objects did not go through that step, because
# 'preprocessData.R' alone leaves every cell at 'BC_0'.
cellmeta <- ensure_global_BC_IDs(cellmeta, ref.Condition)

### collect metadata ###
metadata <- cellmeta %>%
    dplyr::select(Condition, Replicate) %>%
    distinct()

### Count Barcodes ###
bc.counts <- cellmeta %>%
    filter((CaTCH.Status == "Singlet" | CaTCH.Status == "Double_Integration") & CaTCH.BC_ID != "BC_0") %>%
    dplyr::select(CaTCH.BC_unique, Replicate, CaTCH.BC_ID) %>%
    group_by(CaTCH.BC_unique, Replicate) %>%
    mutate(n = n()) %>%
    ungroup() %>%
    distinct() %>%
    pivot_wider(names_from = Replicate, values_from = n, values_fill = 0) %>%
    filter(rowSums(across(starts_with(ref.Condition))) > 0) %>%
    drop_na()

### dplyr::select metadata ###
metadata <- metadata %>%
    mutate(Condition = as.factor(gsub("-", ".", Condition))) %>%
    mutate(Replicate = as.factor(gsub("-", ".", Replicate))) %>%
    dplyr::select(Condition, Replicate)


### Count table for barbieQanalysis.R ###
# barbieQanalysis.R expects the barcode identifier in the first column, an
# optional 'bc_id' column and one count column per sample. The SCE 'Replicate'
# already encodes Condition_Replicate and is therefore the sample level, while
# 'Condition' is the group level.
counts <- bc.counts %>%
    dplyr::rename(barcode = CaTCH.BC_unique, bc_id = CaTCH.BC_ID) %>%
    dplyr::relocate(barcode, bc_id)

colnames(counts) <- c("barcode", "bc_id", gsub("-", ".", colnames(counts)[-c(1, 2)]))

write.table(counts, paste0(opt$out, "_barbieQ_counts.tsv"),
    sep = "\t", quote = FALSE, row.names = FALSE
)

### Design table for barbieQanalysis.R ###
design <- metadata %>%
    dplyr::transmute(
        sample = as.character(Replicate),
        group = as.character(Condition),
        control = as.integer(as.character(Condition) == ref.Condition)
    ) %>%
    filter(sample %in% colnames(counts)) %>%
    distinct()

write.csv(design, paste0(opt$out, "_barbieQ_design.csv"), row.names = FALSE, quote = FALSE)

print(sprintf(
    "Wrote %d barcodes and %d samples (%d group(s), baseline '%s') for barbieQ.",
    nrow(counts), nrow(design), length(unique(design$group)), ref.Condition
))
