library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(ggrepel)
library(gridExtra)

.libPaths("")

library(optparse)

option_list = list(
    make_option(c("--sce"), type="character", default = NULL, 
                help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"),
    make_option(c("--format"), type="character", default = "pdf", 
                help = "format of the plots: pdf (default), jpeg, png, tiff"),
    make_option(c("--width"), type="numeric", default = 25, 
                help = "width of the plot. The units depend on the format: inches for PDF, pixels otherwise"),
    make_option(c("--height"), type = "numeric", default = 10, 
                help = "height of the plot. The units depend on the format: inches for PDF, pixels otherwise"),
    make_option(c("--out"), type="character", default = NULL, 
                help = "path to the output file")
)

opt_parser = OptionParser(option_list = option_list)
opt = parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)){
    print_help(opt_parser)
    stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if ( (length(opt$format) == 0) || !(opt$format %in% c("pdf", "png", "jpeg", "tiff")) ) {
    opt$format <- "pdf"
}

load(opt$sce)

ref.condition <- levels(sce$Condition)[1]

#### Barcode frequencies ####
if (!("BC_ID" %in% names(colData(sce)))) {
  tmp <- colData(sce) %>% 
         as_tibble() %>%
         filter(CaTCH.Status == "Singlet", Condition == ref.condition) %>%
         dplyr::select(CaTCH.BCs, Sample) %>%
         group_by(CaTCH.BCs, Sample) %>%
         mutate(n = n()) %>%
         ungroup() %>%
         distinct() %>%
         pivot_wider(names_from = Sample, values_from = n, values_fill = 0) %>%
         filter(rowSums(across(starts_with(ref.condition))) > 0) %>% 
         mutate(.Means = rowMeans(across(starts_with(ref.condition)))) %>%
         arrange(by = desc(.Means)) %>%
         rowid_to_column(".ID") %>%
         mutate(BC_ID = paste0("BC_", .ID)) %>%
         dplyr::select(-.Means, -.ID) %>%
         relocate(BC_ID, .after = CaTCH.BCs) %>%
         dplyr::select(CaTCH.BCs, BC_ID)
  
  colData(sce)["BC_ID"] <- colData(sce) %>%
                           as_tibble() %>%
                           left_join(y = tmp, by = "CaTCH.BCs") %>%
                           mutate(BC_ID = factor(BC_ID, levels = str_sort(unique(BC_ID), numeric = TRUE))) %>%
                           dplyr::select(BC_ID)
}

plots <- list()
for (t in levels(sce$Condition)) {
  plot.data <- colData(sce) %>%
               as_tibble() %>%
               filter(CaTCH.Status == "Singlet", Condition == t, !is.na(BC_ID)) %>% 
               dplyr::select(Sample, BC_ID) %>%
               group_by(Sample, BC_ID) %>%
               mutate(n = n()) %>%
               ungroup() %>%
               arrange(Sample, desc(n)) %>%
               distinct() %>% 
               pivot_wider(names_from = "Sample", values_from = "n") %>%
               mutate(.Mean = round(rowMeans(across(starts_with(t)), na.rm = TRUE))) %>%
               arrange(desc(.Mean)) %>%
               rowid_to_column(var = ".id") %>%
               mutate(Label = if_else(.id <= 10, paste0(BC_ID, ": ", .Mean), NA_character_))
  p.bccounts <- ggplot(plot.data, aes(x = fct_inorder(as.character(BC_ID)), y = .Mean, label = Label)) + 
                 geom_col() + 
                 geom_label_repel(na.rm = TRUE, show.legend = FALSE) +
                 theme(axis.text.x = element_blank(),
                       axis.ticks.x = element_blank(),
                       panel.grid.major.x = element_blank(),
                       panel.grid.minor.x = element_blank()) +
                 xlab("CaTCH barcodes") + 
                 ylab("Number of cells") + 
                 ggtitle(t)
  plots[[length(plots) + 1]] <- p.bccounts
  
  highlight.bcs <- plot.data %>%
                   filter(!is.na(Label)) %>%
                   dplyr::select(BC_ID) %>%
                   pull()
  p.proportions <- colData(sce) %>%
                   as_tibble() %>%
                   filter(Condition == t) %>%
                   dplyr::select(BC_ID, CaTCH.Status, Cluster) %>%
                   group_by(Cluster) %>%
                   mutate(ClusterSize = n()) %>%
                   ungroup() %>%
                   filter(CaTCH.Status == "Singlet") %>%
                   dplyr::select(-CaTCH.Status) %>%
                   filter(BC_ID %in% highlight.bcs) %>%
                   group_by(BC_ID, Cluster) %>%
                   mutate(BC_prop = n()) %>%
                   distinct() %>% 
                   ungroup() %>%
                   complete(Cluster) %>%
                   ggplot(aes(x = Cluster, fill = BC_ID)) + 
                    geom_col(aes(y = (BC_prop / ClusterSize) * 100)) +
                    ylab("Proportion of cells with\nspecified CaTCH barcodes") + 
                    labs(fill = "CaTCH barcode") + 
                    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  plots[[length(plots) + 1]] <- p.proportions
}

out <- paste0('BC_abundance.',opt$format)
if (opt$format == "png") {
    png(filename = out, width = 1200, height = length(levels(sce$Condition)) * 300)
} else if (opt$format == "jpeg") {
    jpeg(filename = out, width = 1200, height = length(levels(sce$Condition)) * 300)
} else if (opt$format == "tiff") {
    tiff(filename = out, width = 1200, height = length(levels(sce$Condition)) * 300)
} else {
    pdf(file = out, width = 1200, height = length(levels(sce$Condition)) * 300)
}
#jpeg(filename = "BC_abundance.jpeg", width = 1200, height = length(levels(sce$Condition)) * 300)
do.call("grid.arrange", c(plots, ncol = 2))
dev.off()
