library(tidyverse)
library(scater)
library(scran)
library(SingleCellExperiment)
library(DESeq2)
library(dorothea)
library(progeny)
library(circlize)
library(ComplexHeatmap)
library(gridExtra)
library(gtools)
library(viridis)


.libPaths("")

library(optparse)

option_list = list(
    make_option(c("--sce"), type="character", default = NULL, 
                help = "path to the SingleCellExperiment file generated by 'preprocessData.R'"),
    make_option(c("--format"), type="character", default = "pdf", 
                help = "format of the plots: pdf (default), jpeg, png, tiff"),
    make_option(c("--width"), type="numeric", default = 25, 
                help = "width of the plot. The units depend on the format: inches for PDF, pixels otherwise"),
    make_option(c("--height"), type = "numeric", default = 10, 
                help = "height of the plot. The units depend on the format: inches for PDF, pixels otherwise"),
    make_option(c("--out"), type="character", default = NULL, 
                help = "path to the output file")
)

opt_parser = OptionParser(option_list = option_list)
opt = parse_args(opt_parser)

if (is.null(opt$sce) || is.null(opt$out)){
    print_help(opt_parser)
    stop("Not enough parameters")
}

opt$format <- tolower(opt$format)
if ( (length(opt$format) == 0) || !(opt$format %in% c("pdf", "png", "jpeg", "tiff")) ) {
    opt$format <- "pdf"
}

############################# Functions ############################# 
generateHeatmaps <- function(markers, 
                             max.FDR = NULL, 
                             min.FC = NULL, 
                             cluster.rows = TRUE, 
                             cluster.cols = TRUE, 
                             row.title = NULL, 
                             col.title = NULL,
                             min.sigperrow = 0) {
    # Reformat the list of markers so that each entry (DataFrame) becomes a tibble with the rownames (gene symbols) stored in the column "symbol"
    # and the item name. i.e. cluster name, in the column "cluster" of the resulting tibble.
    # Finally, all tibbles are merged into a single big tibble.
    stats_tfa <- map_df(as.list(markers), ~ as_tibble(.x, rownames = "symbol"), .id = "cluster")
    tmp <- stats_tfa
    if (!is.null(max.FDR)) {
        tmp <- tmp %>%
            filter(FDR < max.FDR)
    }
    if (!is.null(min.FC)) {
        tmp <- tmp %>%
            filter(abs(summary.logFC) > min.FC)
    }
    tf_candidates <- tmp %>%
        distinct(symbol) %>%
        pull(symbol)
    
    stats_tfa <- stats_tfa %>%
        filter(symbol %in% tf_candidates)
    
    mat_effect <- stats_tfa %>%
        dplyr::select(cluster, symbol, summary.logFC) %>%
        pivot_wider(names_from = cluster, values_from = summary.logFC) %>%
        data.frame(row.names = "symbol", check.names = FALSE) %>%
        as.matrix()
    mat_stats <- stats_tfa %>%
        dplyr::select(cluster, symbol, FDR) %>%
        pivot_wider(names_from = cluster, values_from = FDR) %>%
        data.frame(row.names = "symbol", check.names = FALSE) %>%
        as.matrix()
    
    stats_value <- 0.05
    mat <- mat_effect
    mat[mat_stats > stats_value] <- 0
    
    # Remove rows with less than min.sigperrow significant values
    tmp <- (mat_stats <= stats_value) %>%
        rowSums()
    idx <- tmp >= min.sigperrow
    mat <- mat[idx, ]
    mat_effect <- mat_effect[idx, ]
    mat_stats <- mat_stats[idx, ]
    
    max_mat <- max(abs(mat_effect), na.rm = TRUE)
    
    col_pwa <- colorRamp2(breaks = c(-max_mat, 0, max_mat), colors = c("blue", "white", "red"))
    
    p_hm_raw <- Heatmap(matrix = mat,
                        name = "log2FC",
                        border = TRUE,
                        cluster_rows = cluster.rows,
                        cluster_columns = cluster.cols,
                        col = col_pwa,
                        column_names_rot = 90,
                        column_names_gp = gpar(fontsize = 12),
                        column_title = col.title,
                        row_names_gp = gpar(fontsize = 10),
                        row_title = row.title,
                        cell_fun = function(j, i, x, y, width, height, fill) {
                            if (mat_stats[i, j] <= stats_value) {
                                grid.text(sprintf("%.1f", mat_effect[i, j]), x, y, gp = gpar(fontsize = 8, col = "black"))
                            } else {
                                grid.text(sprintf("%.1f", mat_effect[i, j]), x, y, gp = gpar(fontsize = 8, col = "grey"))
                            }
                        })
    return (list(heatmap = p_hm_raw, 
                 dims = dim(mat), 
                 symbols = rownames(mat),
                 groups = colnames(mat)))
}
 

##### MAIN #####

#### Load the SingleCellExperiment object generated by processData.R ####
load(opt$sce)

##### Remove the bad cells and the genes with no expression in all samples #####
mask <- (sce$Category == "Good") & (!is.na(sce$CaTCH.Multiplet)) & (!sce$CaTCH.Multiplet)
sce.good <- sce[, mask]
gene.expr <- assay(sce.good, "logcounts") %>%
             rowSums()
sce.good <- sce.good[gene.expr > 0, ]

colData(sce.good)["Treatment"] <- colData(sce.good) %>%
                                  as_tibble() %>%
                                  separate(Sample, sep = "_", into = c("Treatment", "Replicate"), remove = FALSE) %>%
                                  dplyr::select(Treatment)


#### Load the cell counts data ####
LIST <- "/data/gcbds/users/nowoshil/Projects/CaTCH2.0/KRASi_ON_vs_OFF/Exp1010/_tmp4_/outputs/reports/list"

metadata <- read_delim(file = LIST, 
                       col_types = "clc",
                       delim = "\t") %>%
            separate(Sample, sep = "_", into = c("Treatment", "Replicate"), remove = FALSE)

ref.treatment <- metadata %>%
                 filter(Reference) %>%
                 distinct(Treatment) %>%
                 pull()

if(length(ref.treatment) != 1) {
  stop("The samples labeled as Reference must belong to the same treatment. Check the input data")
}

treatments <- metadata %>% 
              dplyr::select(Treatment) %>% 
              filter(Treatment != ref.treatment) %>% 
              pull() %>% 
              unique() %>%
              sort() %>%
              prepend(ref.treatment)


metadata$Treatment <- factor(metadata$Treatment, levels = treatments)

full.data <- NULL
for (i in 1:nrow(metadata)) {
  tmp <- read_delim(file = metadata$Path[i], 
                    col_names = c("CaTCHBarcode", metadata$Sample[i]),
                    col_types = "cd",
                    skip = 1,
                    delim = "\t")
  if (is.null(full.data)) {
    full.data <- tmp
  }
  else {
    full.data <- full.data %>%
                 full_join(y = tmp, by = "CaTCHBarcode")
  }
}

# Sort the CaTCH barcodes by the number of cells in the reference sample and 
# rename them.
full.data <- full.data %>%
             filter_at(vars(-CaTCHBarcode), all_vars(. >= 10)) %>%
             mutate(N = rowMeans(select(., starts_with(ref.treatment)), na.rm = TRUE)) %>%
             arrange(desc(N)) %>%
             mutate(BC_ID = paste("BC", row_number(), sep = "-")) %>%
             dplyr::select(-N)


#### Run DESeq2 to identify over- and underrepresented barcodes ####
cnt.data <- full.data %>%
            column_to_rownames("BC_ID") %>% 
            dplyr::select(-CaTCHBarcode) %>% 
            as.matrix()
cnt.data[is.na(cnt.data)] <- 0

dds <- DESeqDataSetFromMatrix(countData = cnt.data,
                              colData = metadata,
                              design= ~ Treatment)
dds <- DESeq(dds)
results <- list()
plots <- list()
barcodes <- NULL
for (t in setdiff(levels(metadata$Treatment), ref.treatment)) {
  tmp <- results(dds, 
                 alpha = 0.05,
                 contrast = c("Treatment", t, ref.treatment)) %>%
         as_tibble(rownames = NA) %>% 
         rownames_to_column("BC_ID") %>%
         filter(!is.na(padj), padj <= 0.05) %>%
         mutate(Type = if_else(log2FoldChange > 0, "Enriched", "Depleted")) %>%
         arrange(desc(Type), desc(abs(log2FoldChange))) %>%
         inner_join(y = full.data %>% 
                        dplyr::select(BC_ID, starts_with(t), starts_with(ref.treatment)), by = "BC_ID") %>%
         dplyr::select(-baseMean, -lfcSE, -stat, -pvalue, -padj) %>%
         pivot_longer(cols = c(everything(), -BC_ID, -Type, -log2FoldChange), names_to = "Sample", values_to = "CellCount") %>%
         separate(Sample, sep = "_", into = c("Treatment", "Replicate"), remove = FALSE) %>%
         dplyr::select(-Replicate) %>%
         mutate(Treatment = factor(Treatment, levels = treatments),
                CellCount = if_else(is.na(CellCount), 0, CellCount)) %>%
         group_by(BC_ID, Treatment) %>% 
         mutate(CellCount.Mean = mean(CellCount),
                CellCount.SD = sd(CellCount)) %>%
         ungroup() %>%
         mutate(CellCount.Mean = if_else(Type == "Depleted", -CellCount.Mean, CellCount.Mean),
                CellCount.SD = if_else(Type == "Depleted", -CellCount.SD, CellCount.SD),
                BC_ID = factor(BC_ID, levels = unique(BC_ID)))
  
  p <- ggplot(data = tmp, aes(x = BC_ID, y = CellCount.Mean, fill = Treatment)) +
        geom_bar(position = position_dodge(), stat = "identity") + 
        geom_errorbar(aes(ymin = CellCount.Mean - CellCount.SD, 
                          ymax = CellCount.Mean + CellCount.SD), 
                      width = 0.2, position = position_dodge(0.9)) + 
        ggtitle(t) + 
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
        xlab("CaTCH barcode ID") + 
        ylab("Mean cell count")
  
  results[[t]] <- tmp
  plots[[t]] <- p
  barcodes <- c(barcodes, as.character(tmp$BC_ID))
}

barcodes <- mixedsort(unique(barcodes), decreasing = TRUE)
m <- matrix(nrow = length(barcodes), ncol = length(names(results)))
rownames(m) <- barcodes
colnames(m) <- names(results)

plot.lfc  <- map_df(results, .f = function(x){
                    tmp <- x %>% 
                      dplyr::select(BC_ID, log2FoldChange) %>% 
                      distinct()
                    idx <- match(barcodes, tmp$BC_ID)
                    vals <- tmp$log2FoldChange[idx]
                    return(vals)
                  }) %>%
             as.matrix()

rownames(plot.lfc) <- barcodes
hm <- Heatmap(t(plot.lfc), 
              cluster_columns = FALSE, 
              cluster_rows = FALSE, 
              name = "LFC",
              cell_fun = function(i, j, x, y, w, h, f) {
                if (!is.na(plot.lfc[i, j])) {
                  grid.text(sprintf("%.1f", plot.lfc[i, j]), x, y, gp = gpar(fontsize = 6, col = "black"))
                }
              })

plots[["Heatmap"]] <- grid.grabExpr(draw(hm))
do.call("grid.arrange", c(plots, "ncol" = 1))



##### Compare ENRICHED vs DEPLETED barcodes across all treatments #####
# Only keep the cells with the CaTCH barcodes that were identified in
# the previous step
tmp <- full.data %>%
       dplyr::select(CaTCHBarcode, BC_ID) %>%
       filter(BC_ID %in% barcodes)
mask <- sce.good$CaTCH.BCs %in% tmp$CaTCHBarcode
sce.good.diff <- sce.good[, mask]
colData(sce.good.diff)["BC_ID"] <- colData(sce.good.diff) %>%
                                   as_tibble() %>%
                                   left_join(y = full.data %>%
                                                 dplyr::select(CaTCHBarcode, BC_ID),
                                             by = c("CaTCH.BCs" = "CaTCHBarcode")) %>%
                                   dplyr::select(BC_ID)

###### Run PROGENy ###### 
tmp <- assay(sce.good.diff, "logcounts") %>%
       as.matrix()
pw_activities <- progeny(tmp, scale = TRUE, organism = "Human", verbose = TRUE) %>%
                 t()
rm(tmp)
sce.progeny <- SingleCellExperiment(assays = list("progeny" = pw_activities), colData = colData(sce.good.diff))

sce.progeny$Group <- paste(sce.progeny$Treatment, sce.progeny$BC_ID, sep = "_")
markers <- findMarkers(sce.progeny,
                       sce.progeny$Group,
                       direction = "any",
                       pval.type = "some",
                       assay.type = "progeny")
res.progeny <- generateHeatmaps(markers,
                                max.FDR = 0.05,
                                min.FC = 1.5,
                                col.title = "Pathway activities",
                                cluster.cols = TRUE,
                                cluster.rows = FALSE)

##### Plot the heatmap with the PROGENy pathway activities for each treatment and BC #####
hm.data <- t(pw_activities) %>% 
             as_tibble(rownames = NA) %>% 
             rownames_to_column("CellID") %>%
             mutate(Treatment = factor(sce.progeny$Treatment, levels = treatments),
                    BC_ID = sce.progeny$BC_ID) %>%
             relocate(BC_ID) %>%
             pivot_longer(cols = c(everything(), -CellID, -Treatment, -BC_ID), names_to = "Pathway", values_to = "Score") %>%
             group_by(BC_ID, Treatment, Pathway) %>%
             mutate(MeanActivity = mean(Score)) %>%
             ungroup() %>%
             dplyr::select(-CellID) %>%
             dplyr::select(-Score) %>% 
             distinct(BC_ID, Treatment, Pathway, .keep_all = TRUE) %>%
             arrange(Pathway, Treatment) %>%
             pivot_wider(id_cols = c(BC_ID), names_from = c(Pathway, Treatment), values_from = MeanActivity)

tmp <- hm.data %>%
       dplyr::select(-BC_ID) %>%
       as.matrix()
rownames(tmp) <- hm.data$BC_ID
tmp <- t(tmp)
pathways <- rownames(tmp) %>% 
            str_split(string = ., pattern = "_", simplify = TRUE) %>%
            .[,1]
rownames(tmp) <- rownames(tmp) %>% 
                 str_split(string = ., pattern = "_", simplify = TRUE) %>%
                 .[,2]
colors <- viridis(n = length(unique(pathways)), direction = 1)

annotations <- as.data.frame(plot.lfc)
annotations[annotations >= 0] <- "Enriched"
annotations[annotations < 0] <- "Depleted"
annotations[is.na(annotations)] <- "Not significant"
colors <- list()
for (n in colnames(plot.lfc)) {
  colors[[n]] <- c("Depleted" = "purple",
                   "Enriched" = "green",
                   "Not significant" = "grey95")
}
pw.labels <- unique(pathways)
pw.colors <- rep("black", length(pw.labels))
idx <- pw.labels %in% res.progeny$symbols
pw.colors[idx] <- "forestgreen"
idx <- match(rownames(plot.lfc), colnames(tmp))
tmp <- tmp[, idx]
bottom.annot.cellcounts <- full.data %>%
                           filter(BC_ID %in% barcodes) %>%
                           dplyr::select(-CaTCHBarcode) %>% 
                           column_to_rownames("BC_ID") %>%
                           as.matrix()
hm.progeny <- Heatmap(tmp, 
                      cluster_rows = FALSE, 
                      name = "PW activity",
                      row_split = pathways,
                      column_split = apply(X = annotations, 
                                           MARGIN = 1, 
                                           FUN = function(x){
                                             paste(unique(setdiff(x, "Not significant")), collapse = "-")
                                            }),
                      row_gap = unit(3, "mm"),
                      row_names_gp = gpar(fontsize = 9),
                      row_title = NULL,
                      column_names_gp = gpar(fontsize = 9),
                      top_annotation = HeatmapAnnotation(df = annotations, 
                                                         col = colors,
                                                         show_legend = FALSE),
                      #bottom_annotation = HeatmapAnnotation(Cells = anno_barplot(bottom.annot.cellcounts,
                      #                                                           gp = gpar(fill = 1:nrow(bottom.annot.cellcounts))),
                      #                                      show_legend = TRUE),
                      left_annotation = rowAnnotation(pathways = anno_block(gp = gpar(fill = pw.colors, col = "grey50"),
                                                                            labels = pw.labels,
                                                                            labels_gp = gpar(col = "white", fontsize = 8))))



###### DoRoThEA ######
dorothea_regulon_human <- get(data("dorothea_hs", package = "dorothea")) %>%
                          filter(confidence %in% c("A", "B", "C"))

sce.dorothea <- run_viper(sce.good.diff,
                          dorothea_regulon_human,
                          options = list(method = "scale", minsize = 10, eset.filter = FALSE, cores = 1, verbose = FALSE))

colData(altExp(sce.dorothea, "dorothea")) <- colData(sce.good.diff)
sce.dorothea$Group <- paste(sce.dorothea$Treatment, sce.dorothea$BC_ID, sep = "_")
markers <- findMarkers(altExp(sce.dorothea, "dorothea"),
                       sce.dorothea$Group,
                       direction = "any",
                       pval.type = "some",
                       assay.type = "tf_activities")
res.dorothea <- generateHeatmaps(markers,
                                 max.FDR = 0.05,
                                 min.FC = 2,
                                 col.title = "TF activities",
                                 cluster.cols = TRUE,
                                 cluster.rows = TRUE,
                                 min.sigperrow = 10)

